# SPDX-License-Identifier: BSD-2-Clause-FreeBSD
#
# protocol-coverage-matrix — Phase 2 of the protocol-coverage-matrix
# plan (see /home/das/.claude/profiles/personal/plans/
# in-this-folder-is-fuzzy-wigderson.md).
#
# Runs flow-dissector-parity-check once per protocol-template PCAP
# in samples/proto_audit/pcap_templates/ (378 single-packet shapes
# generated by helpers/gen_pcap_templates.py), sharded into a
# per-protocol JSONL tree, then aggregates into a single
# (protocol × parser) markdown + CSV matrix via
# nix/scripts/protocol-coverage-matrix.py.
#
#   nix run .#protocol-coverage-matrix -- [--out DIR]
#                                         [--parsers CSV]
#                                         [--bootstrap-expectations]
#                                         [--require-expectations]
#                                         [--jobs N]
#                                         [--limit N]
#
# Default OUT: $(mktemp -d -t xdp2-cov-XXXX). Default --parsers
# excludes c-bpf-flowdis + c-bpf-fast (CAP_BPF; same as
# nix/checks/parity-gate.nix:92-97). Operators on a lab host can
# pass --parsers to add those.
#
# Output tree:
#   $OUT/jsonl/<protocol>/<parser_id>.jsonl   per-cell raw records
#   $OUT/logs/<protocol>.log                  driver stdout+stderr
#   $OUT/report/matrix.md                     aggregated report
#   $OUT/report/matrix.csv
#   $OUT/report/scope-additions.json          if --bootstrap-expectations

{ pkgs, parityCheck, lib }:

let
  pcapDir = ../samples/proto_audit/pcap_templates;
  scopeFile = ../samples/flow_dissector/parity_scope.json;
  aggregator = ./scripts/protocol-coverage-matrix.py;
  parityCompareScript = ./scripts/parity-compare.py;

  # Mirror parity-gate.nix:98-112: drop c-bpf-flowdis and c-bpf-fast.
  defaultParsers = lib.concatStringsSep "," [
    "c-flowdis-usp"
    "c-xdp2-usp"
    "c-xdp2-parse-only"
    "c-xdp2-mono"
    "c-bpf-xdp2"
    "rust-graph"
    "rust-graph-enum"
    "rust-mono"
    "rust-mono-x4"
    "rust-compiled"
    "rust-simd"
    "rust-template"
    "rust-template-simd"
  ];
in
pkgs.writeShellApplication {
  name = "protocol-coverage-matrix";

  runtimeInputs = [
    parityCheck
    pkgs.coreutils
    pkgs.findutils
    pkgs.python3
  ];

  text = ''
    set -eu

    usage() {
      cat <<'USAGE'
    Usage:
      protocol-coverage-matrix [OPTIONS]

    Runs flow-dissector-parity-check against every per-protocol
    pcap template and renders a (protocol × parser) matrix.

    Options:
      --out DIR              Output directory. Default: $(mktemp -d).
      --parsers CSV          Comma-separated parser_ids. Default:
                             all non-BPF (same set as parity-gate).
      --bootstrap-expectations
                             Also emit scope-additions.json — a
                             starter `expected_protocol_acceptance`
                             snippet observing current behavior, for
                             human review and merge into
                             samples/flow_dissector/parity_scope.json.
      --require-expectations
                             Exit non-zero if any cell is classified
                             REJ-unexpected. Default: report-only.
      --jobs N               Run N pcaps in parallel. Default: 1.
      --limit N              Only process the first N pcaps (sorted
                             alphabetically). Useful for smoke runs.
      -h, --help             Show this help.

    Output:
      $OUT/jsonl/<protocol>/<parser>.jsonl   per-cell raw records
      $OUT/logs/<protocol>.log               driver log per pcap
      $OUT/report/matrix.md                  aggregated report
      $OUT/report/matrix.csv
      $OUT/report/scope-additions.json       if --bootstrap-expectations
    USAGE
    }

    OUT=""
    PARSERS='${defaultParsers}'
    BOOTSTRAP=0
    REQUIRE_EXPECT=0
    JOBS=1
    LIMIT=0

    while [ $# -gt 0 ]; do
      case "$1" in
        -h|--help) usage; exit 0 ;;
        --out)
          [ $# -ge 2 ] || { echo "protocol-coverage-matrix: --out requires DIR" >&2; exit 2; }
          OUT="$2"; shift 2 ;;
        --parsers)
          [ $# -ge 2 ] || { echo "protocol-coverage-matrix: --parsers requires CSV" >&2; exit 2; }
          PARSERS="$2"; shift 2 ;;
        --bootstrap-expectations) BOOTSTRAP=1; shift ;;
        --require-expectations) REQUIRE_EXPECT=1; shift ;;
        --jobs)
          [ $# -ge 2 ] || { echo "protocol-coverage-matrix: --jobs requires N" >&2; exit 2; }
          JOBS="$2"; shift 2 ;;
        --limit)
          [ $# -ge 2 ] || { echo "protocol-coverage-matrix: --limit requires N" >&2; exit 2; }
          LIMIT="$2"; shift 2 ;;
        *) echo "protocol-coverage-matrix: unknown argument '$1'" >&2; usage >&2; exit 2 ;;
      esac
    done

    if [ -z "$OUT" ]; then
      OUT=$(mktemp -d -t xdp2-cov-XXXXXX)
    fi
    mkdir -p "$OUT/jsonl" "$OUT/logs" "$OUT/report"

    PCAP_DIR='${pcapDir}'
    SCOPE_PATH='${scopeFile}'
    AGG_SCRIPT='${aggregator}'
    PARITY_COMPARE_SCRIPT='${parityCompareScript}'

    # Ensure the aggregator can find its sibling parity-compare.py
    # at runtime (importlib.util.spec_from_file_location looks
    # relative to __file__). Materialise both into a workdir.
    WORK=$(mktemp -d -t xdp2-cov-work-XXXX)
    cp "$AGG_SCRIPT" "$WORK/protocol-coverage-matrix.py"
    cp "$PARITY_COMPARE_SCRIPT" "$WORK/parity-compare.py"

    echo "[coverage] pcap-dir=$PCAP_DIR" >&2
    echo "[coverage] out=$OUT jobs=$JOBS" >&2

    # Build list of (protocol, pcap) pairs.
    mapfile -t pcaps < <(find "$PCAP_DIR" -maxdepth 1 -name '*.pcap' | sort)
    if [ "$LIMIT" -gt 0 ]; then
      pcaps=( "''${pcaps[@]:0:$LIMIT}" )
    fi
    echo "[coverage] processing ''${#pcaps[@]} pcaps" >&2

    run_one() {
      local pcap="$1"
      local proto
      proto=$(basename "$pcap" .pcap)
      local proto_out="$OUT/jsonl/$proto"
      mkdir -p "$proto_out"
      # Touch one empty jsonl per requested parser before invoking
      # the driver. This way "file empty after run" means "parser
      # was attempted but produced nothing" (matrix classifies as
      # bench-failed), distinct from "file missing" (parser not
      # requested → N/A). The Rust xdp2-bench path in
      # nix/flow-dissector-parity-check.nix:185-188 doesn't always
      # create its --dump-meta target on failure, so we pre-create.
      local IFS=','
      for pid in $PARSERS; do
        : > "$proto_out/$pid.jsonl"
      done
      unset IFS
      # Report-only: tolerate parity-check exit codes; matrix
      # aggregates whatever JSONLs land.
      flow-dissector-parity-check \
        --pcap "$pcap" \
        --out "$proto_out" \
        --parsers "$PARSERS" \
        > "$OUT/logs/$proto.log" 2>&1 || true
    }
    export -f run_one
    export OUT PARSERS

    if [ "$JOBS" -gt 1 ]; then
      # -I{} implies -n 1 in xargs; pass just -I to avoid the
      # "options --max-args and --replace/-I are mutually exclusive"
      # warning.
      printf '%s\n' "''${pcaps[@]}" \
        | xargs -P "$JOBS" -I{} bash -c 'run_one "$@"' _ {}
    else
      for pcap in "''${pcaps[@]}"; do
        run_one "$pcap"
      done
    fi

    AGG_ARGS=( --jsonl-tree "$OUT/jsonl"
               --scope "$SCOPE_PATH"
               --out "$OUT/report" )
    if [ "$BOOTSTRAP" -eq 1 ]; then
      AGG_ARGS+=( --bootstrap-expectations )
    fi
    if [ "$REQUIRE_EXPECT" -eq 1 ]; then
      AGG_ARGS+=( --require-expectations )
    fi

    python3 "$WORK/protocol-coverage-matrix.py" "''${AGG_ARGS[@]}"

    echo "[coverage] matrix: $OUT/report/matrix.md" >&2
    if [ "$BOOTSTRAP" -eq 1 ]; then
      echo "[coverage] scope additions: $OUT/report/scope-additions.json" >&2
    fi
  '';

  meta = {
    description = "Run flow-dissector parity-check over all proto-audit pcap templates and aggregate into a (protocol × parser) matrix";
    mainProgram = "protocol-coverage-matrix";
  };
}
