#!/bin/bash
echo "🧪 Interactive XDP2 Development Shell Test"
echo "==========================================="
echo "Entering development shell for manual testing..."
echo ""
echo "Available commands to test:"
echo "  build-cppfront     - Build cppfront compiler"
echo "  build-xdp2-compiler - Build xdp2 compiler"
echo "  build-xdp2         - Build main XDP2 project"
echo "  build-all          - Build all components"
echo "  clean-build        - Clean all build artifacts"
echo "  run-shellcheck     - Validate all shell functions"
echo "  check-cppfront-age - Check and rebuild cppfront if needed"
echo ""
echo "Convenient aliases:"
echo "  xdp2-build        - Alias for 'build-all'"
echo "  xdp2-clean        - Alias for 'clean-build'"
echo "  xdp2-check        - Alias for 'run-shellcheck'"
echo "  xdp2-help         - Show available commands"
echo "  xdp2-src          - Navigate to src/ directory"
echo "  xdp2-samples      - Navigate to samples/ directory"
echo "  xdp2-docs         - Navigate to documentation/ directory"
echo "  xdp2-cppfront     - Navigate to cppfront directory"
echo ""
echo "Debug levels:"
echo "  XDP2_NIX_DEBUG=1-7 - Set debug verbosity level"
echo ""
echo "Example test sequence:"
echo "  1. xdp2-help"
echo "  2. xdp2-build"
echo "  3. xdp2-check"
echo "  4. xdp2-clean"
echo ""
echo "Press Ctrl+D or type 'exit' to leave the shell"
echo "==========================================="
echo ""
nix develop --no-write-lock-file
