#define XDP2_DFTABLE_PLAIN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_PLAIN_TABLE_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		PLAIN, plain,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_PLAIN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_PLAIN_TABLE_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, plain, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_PLAIN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_PLAIN_TABLE_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_PLAIN_TABLE_NAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		PLAIN, plain,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_NAME(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_PLAIN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_PLAIN_TABLE_NAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, plain, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_NAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_NAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_PLAIN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_PLAIN_TABLE_NAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_PLAIN_TABLE_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		PLAIN, plain,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_PLAIN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_PLAIN_TABLE_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, plain, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_PLAIN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_PLAIN_TABLE_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_PLAIN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		PLAIN, plain,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_PLAIN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_PLAIN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, plain, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_PLAIN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_PLAIN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_PLAIN_TABLE_ANAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		PLAIN, plain,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_ANAME(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_PLAIN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_PLAIN_TABLE_ANAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, plain, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_ANAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_ANAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_PLAIN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_PLAIN_TABLE_ANAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_PLAIN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		PLAIN, plain,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_PLAIN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_PLAIN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, plain, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_PLAIN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_PLAIN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_TERN_TABLE_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		TERN, tern,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_TERN_TABLE(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_TERN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_TERN_TABLE_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_TERN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, tern, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_TERN_TABLE(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_TERN_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_TERN_TABLE_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_TERN_TABLE_NAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		TERN, tern,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_NAME(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_TERN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_TERN_TABLE_NAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_TERN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, tern, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_NAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_TERN_TABLE_NAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_TERN_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_TERN_TABLE_NAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_TERN_TABLE_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		TERN, tern,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_TERN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_TERN_TABLE_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_TERN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, tern, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_TERN_TABLE_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_TERN_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_TERN_TABLE_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_TERN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		TERN, tern,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_TERN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_TERN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_TERN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, tern, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_TERN_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_TERN_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_TERN_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_TERN_TABLE_ANAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		TERN, tern,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_ANAME(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_TERN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_TERN_TABLE_ANAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_TERN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, tern, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_ANAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_TERN_TABLE_ANAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_TERN_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_TERN_TABLE_ANAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_TERN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		TERN, tern,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_TERN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_TERN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_TERN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, tern, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_TERN_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_TERN_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_TERN_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_LPM_TABLE_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		LPM, lpm,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_LPM_TABLE(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_LPM_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_LPM_TABLE_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_LPM_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, lpm, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_LPM_TABLE(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_LPM_TABLE_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_LPM_TABLE_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_LPM_TABLE_NAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		LPM, lpm,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_NAME(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_LPM_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_LPM_TABLE_NAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_LPM_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, lpm, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_NAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_LPM_TABLE_NAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_LPM_TABLE_NAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_LPM_TABLE_NAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_LPM_TABLE_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		LPM, lpm,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_LPM_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_LPM_TABLE_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_LPM_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, lpm, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_LPM_TABLE_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_LPM_TABLE_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_LPM_TABLE_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_LPM_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		LPM, lpm,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_LPM_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_LPM_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_LPM_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, lpm, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_LPM_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_LPM_TABLE_NAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_LPM_TABLE_NAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_LPM_TABLE_ANAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		LPM, lpm,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_ANAME(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_LPM_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_LPM_TABLE_ANAME_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_LPM_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, lpm, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_ANAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_LPM_TABLE_ANAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_LPM_TABLE_ANAME_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_LPM_TABLE_ANAME_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_LPM_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		LPM, lpm,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_LPM_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_LPM_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_LPM_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, lpm, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_LPM_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_LPM_TABLE_ANAME_CAST_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_LPM_TABLE_ANAME_CAST_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
					     plain)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME, KEY_ARG_TYPE)

#define XDP2_DFTABLE_PLAIN_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_ACTION,		\
		NULL, PLAIN, plain, XDP2_JOIN2(NAME, _key_arg_t),	\
		CONFIG)

#define XDP2_DFTABLE_PLAIN_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       DEFAULT_ACTION, CONFIG)		\
	XDP2_DFTABLE_PLAIN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	XDP2_DFTABLE_PLAIN_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	__XDP2_DTABLE_PLAIN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC_SKEY(				\
		NAME, KEY_ARG_TYPE, plain, TARG_TYPE)			\
	__XDP2_DTABLE_LOOKUP_TABLE_PLAIN_FUNCS(NAME, KEY_ARG_TYPE,	\
						TARG_TYPE)

#define XDP2_DTABLE_PLAIN_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, PLAIN,	\
				       plain,				\
				       XDP2_JOIN2(NAME, _key_arg_t),	\
				       CONFIG)

#define XDP2_DTABLE_PLAIN_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG, CONFIG)		\
	XDP2_DTABLE_PLAIN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	XDP2_DTABLE_PLAIN_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
					     tern)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME, KEY_ARG_TYPE)

#define XDP2_DFTABLE_TERN_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_ACTION,		\
		NULL, TERN, tern, XDP2_JOIN2(NAME, _key_arg_t),	\
		CONFIG)

#define XDP2_DFTABLE_TERN_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       DEFAULT_ACTION, CONFIG)		\
	XDP2_DFTABLE_TERN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	XDP2_DFTABLE_TERN_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)

#define XDP2_DTABLE_TERN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	__XDP2_DTABLE_TERN_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC_SKEY(				\
		NAME, KEY_ARG_TYPE, tern, TARG_TYPE)			\
	__XDP2_DTABLE_LOOKUP_TABLE_TERN_FUNCS(NAME, KEY_ARG_TYPE,	\
						TARG_TYPE)

#define XDP2_DTABLE_TERN_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, TERN,	\
				       tern,				\
				       XDP2_JOIN2(NAME, _key_arg_t),	\
				       CONFIG)

#define XDP2_DTABLE_TERN_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG, CONFIG)		\
	XDP2_DTABLE_TERN_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	XDP2_DTABLE_TERN_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
					     lpm)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME, KEY_ARG_TYPE)

#define XDP2_DFTABLE_LPM_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_ACTION,		\
		NULL, LPM, lpm, XDP2_JOIN2(NAME, _key_arg_t),	\
		CONFIG)

#define XDP2_DFTABLE_LPM_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       DEFAULT_ACTION, CONFIG)		\
	XDP2_DFTABLE_LPM_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	XDP2_DFTABLE_LPM_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)

#define XDP2_DTABLE_LPM_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	__XDP2_DTABLE_LPM_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC_SKEY(				\
		NAME, KEY_ARG_TYPE, lpm, TARG_TYPE)			\
	__XDP2_DTABLE_LOOKUP_TABLE_LPM_FUNCS(NAME, KEY_ARG_TYPE,	\
						TARG_TYPE)

#define XDP2_DTABLE_LPM_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, LPM,	\
				       lpm,				\
				       XDP2_JOIN2(NAME, _key_arg_t),	\
				       CONFIG)

#define XDP2_DTABLE_LPM_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG, CONFIG)		\
	XDP2_DTABLE_LPM_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	XDP2_DTABLE_LPM_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)

