#define XDP2_SFTABLE_PLAIN_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_PLAIN_TABLE(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_PLAIN_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_NAME_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_NAME_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_PLAIN_TABLE_NAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_PLAIN_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_PLAIN_TABLE_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_PLAIN_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_NAME_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_NAME_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_PLAIN_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_PLAIN_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_ANAME_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_ANAME_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_PLAIN_TABLE_ANAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_PLAIN_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_ANAME_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_ANAME_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_PLAIN_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_TERN_TABLE(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_NAME_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_NAME_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_TERN_TABLE_NAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_TERN_TABLE_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_NAME_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_NAME_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_TERN_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_ANAME_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_ANAME_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_TERN_TABLE_ANAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_ANAME_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_ANAME_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_TERN_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_LPM_TABLE(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_NAME_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE_NAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_NAME_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_LPM_TABLE_NAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_LPM_TABLE_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_NAME_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE_NAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_NAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_NAME_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_NAME_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_LPM_TABLE_NAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_ANAME_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE_ANAME(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_ANAME_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_LPM_TABLE_ANAME(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_SFTABLE_TABLE_COMMON(NAME, COMMON_ARGS_SIG, ACTIONS,	\
				    DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					       COMMON_ARGS_SIG,		\
					       COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_ANAME_CAST_ENTS(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, COMMON_ARGS_SIG,		\
		COMMON_ARGS_LIST, ACTIONS, DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(			\
		NAME, ENTRIES, COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE_ANAME_CAST(				\
		NAME, KEY_ARG_TYPE, KEY_DEF, TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT_ANAME_CAST(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC_ANAME_CAST(NAME, KEY_DEF)			\
	__XDP2_STABLE_TABLE_COMMON(NAME, TARG_TYPE)			\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC(NAME, KEY_ARG_TYPE,	\
					      TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_ANAME_CAST_ENTS(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE,	\
					     DEFAULT_TARG, ENTRIES)	\
	XDP2_STABLE_LPM_TABLE_ANAME_CAST(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG)	\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_PLAIN_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_SFTABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), COMMON_ARGS_SIG)	\
	__XDP2_SFTABLE_MAKE_ACTIONS_TABLE(NAME, ACTIONS)		\
	__XDP2_SFTABLE_MAKE_DEFAULT_FUNC(NAME, COMMON_ARGS_SIG,		\
					 DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, plain)	\
	__XDP2_SFTABLE_MAKE_LOOKUP_PLAIN_FUNC_SKEY(			\
		NAME, KEY_ARG_TYPE, COMMON_ARGS_SIG, COMMON_ARGS_LIST)

#define XDP2_SFTABLE_PLAIN_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					    COMMON_ARGS_SIG,		\
					    COMMON_ARGS_LIST, ACTIONS,	\
					    DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_PLAIN_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES,		\
						 COMMON_ARGS_SIG)

#define XDP2_STABLE_PLAIN_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_STABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), TARG_TYPE)		\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       plain)				\
	__XDP2_STABLE_MAKE_LOOKUP_PLAIN_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
						   TARG_TYPE)

#define XDP2_STABLE_PLAIN_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE, DEFAULT_TARG,	\
					   ENTRIES)			\
	XDP2_STABLE_PLAIN_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_STABLE_MAKE_PLAIN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_TERN_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_SFTABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), COMMON_ARGS_SIG)	\
	__XDP2_SFTABLE_MAKE_ACTIONS_TABLE(NAME, ACTIONS)		\
	__XDP2_SFTABLE_MAKE_DEFAULT_FUNC(NAME, COMMON_ARGS_SIG,		\
					 DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, tern)	\
	__XDP2_SFTABLE_MAKE_LOOKUP_TERN_FUNC_SKEY(			\
		NAME, KEY_ARG_TYPE, COMMON_ARGS_SIG, COMMON_ARGS_LIST)

#define XDP2_SFTABLE_TERN_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					    COMMON_ARGS_SIG,		\
					    COMMON_ARGS_LIST, ACTIONS,	\
					    DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_TERN_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES,		\
						 COMMON_ARGS_SIG)

#define XDP2_STABLE_TERN_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_STABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), TARG_TYPE)		\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       tern)				\
	__XDP2_STABLE_MAKE_LOOKUP_TERN_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
						   TARG_TYPE)

#define XDP2_STABLE_TERN_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE, DEFAULT_TARG,	\
					   ENTRIES)			\
	XDP2_STABLE_TERN_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_STABLE_MAKE_TERN_MATCH_ENTRIES(NAME, ENTRIES)

#define XDP2_SFTABLE_LPM_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_SFTABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), COMMON_ARGS_SIG)	\
	__XDP2_SFTABLE_MAKE_ACTIONS_TABLE(NAME, ACTIONS)		\
	__XDP2_SFTABLE_MAKE_DEFAULT_FUNC(NAME, COMMON_ARGS_SIG,		\
					 DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, lpm)	\
	__XDP2_SFTABLE_MAKE_LOOKUP_LPM_FUNC_SKEY(			\
		NAME, KEY_ARG_TYPE, COMMON_ARGS_SIG, COMMON_ARGS_LIST)

#define XDP2_SFTABLE_LPM_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					    COMMON_ARGS_SIG,		\
					    COMMON_ARGS_LIST, ACTIONS,	\
					    DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_LPM_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES,		\
						 COMMON_ARGS_SIG)

#define XDP2_STABLE_LPM_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_STABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), TARG_TYPE)		\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       lpm)				\
	__XDP2_STABLE_MAKE_LOOKUP_LPM_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
						   TARG_TYPE)

#define XDP2_STABLE_LPM_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE, DEFAULT_TARG,	\
					   ENTRIES)			\
	XDP2_STABLE_LPM_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_STABLE_MAKE_LPM_MATCH_ENTRIES(NAME, ENTRIES)

