//! Code generators: IR ProtocolDef → target language output.
//!
//! Supports three targets:
//! - **C** (XDP2 proto_def header): the original generator
//! - **etherparse** (Rust struct): generates `pub struct` with derives
//! - **Scapy** (Python Packet class): generates `fields_desc` + `bind_layers`

use crate::ir::{Endian, FieldType, ProtocolDef};
use crate::name_mapping;
use crate::type_mapping;

/// Generate a complete XDP2 proto_def C header from a ProtocolDef.
pub fn generate_proto_def(proto: &ProtocolDef) -> String {
    let canonical = &proto.name;

    // Look up names from the mapping table
    let names = name_mapping::find_by_canonical(canonical);

    let snake = canonical_to_snake(canonical);
    let upper = canonical_to_upper(canonical);
    let guard = format!("__XDP2_PROTO_{}_H__", upper);

    let kernel_header = names
        .as_ref()
        .and_then(|n| n.kernel_header)
        .unwrap_or("linux/types.h");

    let kernel_struct = names
        .as_ref()
        .and_then(|n| n.kernel_struct)
        .unwrap_or("unknown_hdr");

    let has_next_proto = proto.dispatch_field.is_some();
    let has_variable_len = proto.is_variable_length;

    let mut out = String::new();

    // SPDX + license header
    out.push_str(&format!(
        "/* SPDX-License-Identifier: BSD-2-Clause-FreeBSD\n\
         *\n\
         * Auto-generated by proto-audit from IR definition.\n\
         * Protocol: {}\n\
         */\n\n",
        canonical
    ));

    // Include guard
    out.push_str(&format!("#ifndef {}\n", guard));
    out.push_str(&format!("#define {}\n\n", guard));

    // Includes
    out.push_str(&format!("#include <{}>\n\n", kernel_header));
    out.push_str("#include \"xdp2/parser.h\"\n\n");

    // Helper: next_proto function
    if has_next_proto {
        if let Some(ref dispatch_field) = proto.dispatch_field {
            // Find the actual kernel field name for the dispatch field
            let kernel_field = proto
                .fields
                .iter()
                .find(|f| &f.name == dispatch_field)
                .and_then(|f| f.source_names.get("kernel"))
                .map(|s| s.as_str())
                .unwrap_or(dispatch_field.as_str());

            out.push_str(&format!(
                "static inline int {}_proto(const void *vhdr)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{};\n\
                 }}\n\n",
                snake, kernel_struct, kernel_field
            ));
        }
    }

    // Helper: variable length function
    if has_variable_len {
        // Find the length field
        let len_field = proto.fields.iter().find(|f| f.is_length);

        if let Some(lf) = len_field {
            let kernel_field = lf
                .source_names
                .get("kernel")
                .map(|s| s.as_str())
                .unwrap_or(&lf.name);

            let multiplier = lf.length_multiplier.unwrap_or(1);

            out.push_str(&format!(
                "static inline ssize_t {}_length(const void *vhdr, size_t maxlen)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{}{};  \n\
                 }}\n\n",
                snake,
                kernel_struct,
                kernel_field,
                if multiplier > 1 {
                    format!(" * {}", multiplier)
                } else {
                    String::new()
                }
            ));
        }
    }

    // End of regular header section
    out.push_str(&format!("#endif /* {} */\n\n", guard));

    // Conditional proto_def struct
    out.push_str("#ifdef XDP2_DEFINE_PARSE_NODE\n\n");

    // Proto_def comment
    out.push_str(&format!(
        "/* xdp2_parse_{} protocol definition\n\
         *\n\
         * Parse {} header\n",
        snake, canonical
    ));
    if has_next_proto {
        out.push_str(" *\n * Next protocol operation returns protocol identifier\n");
    }
    out.push_str(" */\n");

    // Proto_def struct
    out.push_str(&format!(
        "static const struct xdp2_proto_def xdp2_parse_{} __unused() = {{\n",
        snake
    ));
    out.push_str(&format!("\t.name = \"{}\",\n", canonical));
    out.push_str(&format!(
        "\t.min_len = sizeof(struct {}),\n",
        kernel_struct
    ));
    if has_variable_len {
        out.push_str(&format!("\t.ops.len = {}_length,\n", snake));
    }
    if has_next_proto {
        out.push_str(&format!("\t.ops.next_proto = {}_proto,\n", snake));
    }
    out.push_str("};\n\n");

    out.push_str("#endif /* XDP2_DEFINE_PARSE_NODE */\n");

    out
}

/// Convert "IPv4" → "ipv4", "TCP" → "tcp", "IEEE802.11" → "ieee802_11"
fn canonical_to_snake(name: &str) -> String {
    name.to_lowercase()
        .replace('.', "_")
        .replace('-', "_")
        .replace(' ', "_")
}

/// Convert "IPv4" → "IPV4", "TCP" → "TCP"
fn canonical_to_upper(name: &str) -> String {
    name.to_uppercase()
        .replace('.', "_")
        .replace('-', "_")
        .replace(' ', "_")
}

// ── etherparse generator ──

/// Generate a Rust struct definition for etherparse from a ProtocolDef.
pub fn generate_etherparse(proto: &ProtocolDef) -> String {
    let mappings = type_mapping::load_etherparse_gen_mappings(None)
        .expect("embedded etherparse_gen mappings should always parse");

    let struct_name = canonical_to_pascal(&proto.name);
    let snake = canonical_to_snake(&proto.name);

    let mut out = String::new();

    // Header comment
    out.push_str(&format!(
        "// Auto-generated by proto-audit from IR definition.\n\
         // Protocol: {}\n\
         // Minimum header: {} bytes\n\n",
        proto.name,
        proto.min_header_bits / 8
    ));

    // Derives
    let derives = if mappings.derives.default.is_empty() {
        vec![
            "Debug".to_string(),
            "Clone".to_string(),
            "PartialEq".to_string(),
            "Eq".to_string(),
        ]
    } else {
        mappings.derives.default.clone()
    };
    out.push_str(&format!("#[derive({})]\n", derives.join(", ")));

    // Struct definition
    out.push_str(&format!("pub struct {}Header {{\n", struct_name));

    let mut bitfield_group: Vec<(&str, u32)> = Vec::new();

    for field in &proto.fields {
        // Skip fields that etherparse typically omits
        if mappings.should_skip(&format!("{}Header", struct_name), &field.name) {
            continue;
        }

        // Check for newtype override first, then generic type mapping
        let rust_type = if let Some(nt) = mappings.newtype(&field.name) {
            nt.to_string()
        } else if let Some(rt) = mappings.rust_type(&field.field_type, field.size_bits) {
            rt.to_string()
        } else {
            // Fallback: pick smallest Rust integer that fits
            rust_type_for_bits(field.size_bits)
        };

        // Handle single-bit flags as bool fields
        if field.field_type == FieldType::Flags && field.size_bits == 1 {
            out.push_str(&format!("    pub {}: bool,\n", field.name));
            continue;
        }

        // Handle multi-bit sub-byte fields: group contiguous bitfields
        if field.size_bits < 8 && !is_byte_aligned(field.offset_bits, field.size_bits) {
            bitfield_group.push((&field.name, field.size_bits));
            continue;
        }

        // Flush any pending bitfield group
        flush_bitfield_group(&mut out, &mut bitfield_group);

        // Doc comment with description
        if !field.description.is_empty() {
            out.push_str(&format!("    /// {}\n", field.description));
        }

        out.push_str(&format!("    pub {}: {},\n", field_name_rust(&field.name), rust_type));
    }

    // Flush any remaining bitfield group
    flush_bitfield_group(&mut out, &mut bitfield_group);

    out.push_str("}\n\n");

    // Size assertion
    let min_bytes = proto.min_header_bits / 8;
    out.push_str(&format!(
        "// Wire format: {} bytes minimum\n",
        min_bytes
    ));

    // impl block with from_bytes / to_bytes skeleton
    out.push_str(&format!("impl {}Header {{\n", struct_name));
    out.push_str(&format!("    /// Minimum header size in bytes.\n"));
    out.push_str(&format!("    pub const MIN_LEN: usize = {};\n\n", min_bytes));
    out.push_str(&format!("    /// Read from a byte slice.\n"));
    out.push_str(&format!(
        "    pub fn from_slice(slice: &[u8]) -> Result<{}Header, err::LenError> {{\n",
        struct_name
    ));
    out.push_str("        if slice.len() < Self::MIN_LEN {\n");
    out.push_str("            return Err(err::LenError {\n");
    out.push_str("                required_len: Self::MIN_LEN,\n");
    out.push_str("                len: slice.len(),\n");
    out.push_str("                len_source: err::LenSource::Slice,\n");
    out.push_str(&format!("                layer: err::Layer::{},\n", snake));
    out.push_str("                layer_start_offset: 0,\n");
    out.push_str("            });\n");
    out.push_str("        }\n");
    out.push_str(&format!(
        "        todo!(\"parse {} fields from slice\")\n",
        struct_name
    ));
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Generate a Python Scapy Packet class definition from a ProtocolDef.
pub fn generate_scapy(proto: &ProtocolDef) -> String {
    let mappings = type_mapping::load_scapy_gen_mappings(None)
        .expect("embedded scapy_gen mappings should always parse");

    let class_name = canonical_to_pascal(&proto.name);

    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "# Auto-generated by proto-audit from IR definition.\n\
         # Protocol: {}\n\n",
        proto.name
    ));

    // Imports
    out.push_str("from scapy.packet import Packet, bind_layers\n");
    out.push_str("from scapy.fields import *\n\n\n");

    // Class definition
    out.push_str(&format!("class {}(Packet):\n", class_name));
    out.push_str(&format!("    name = \"{}\"\n", proto.name));
    out.push_str("    fields_desc = [\n");

    for field in &proto.fields {
        let scapy_name = field
            .source_names
            .get("scapy")
            .map(|s| s.as_str())
            .unwrap_or(&field.name);

        // Determine field class
        let field_class = determine_scapy_class(&field.field_type, field.size_bits,
                                                 scapy_name, &field.endian,
                                                 &field.flag_names, &mappings);

        // Build field constructor
        let field_str = format_scapy_field(&field_class, scapy_name, field.size_bits,
                                           &field.field_type, &field.default_value,
                                           &field.flag_names);

        out.push_str(&format!("        {},\n", field_str));
    }

    out.push_str("    ]\n");

    // bind_layers from dispatch table
    if !proto.dispatch_table.is_empty() {
        out.push_str("\n\n");
        for entry in &proto.dispatch_table {
            if let Some(ref dispatch_field) = proto.dispatch_field {
                let dispatch_name = proto
                    .fields
                    .iter()
                    .find(|f| &f.name == dispatch_field)
                    .and_then(|f| f.source_names.get("scapy"))
                    .map(|s| s.as_str())
                    .unwrap_or(dispatch_field.as_str());

                out.push_str(&format!(
                    "bind_layers({}, {}, {}={})\n",
                    class_name,
                    canonical_to_pascal(&entry.protocol),
                    dispatch_name,
                    format_value(entry.value)
                ));
            }
        }
    }

    out
}

/// Determine the Scapy field class for a given IR field.
fn determine_scapy_class(
    ft: &FieldType,
    bits: u32,
    name: &str,
    endian: &Endian,
    flag_names: &Option<Vec<String>>,
    mappings: &type_mapping::ScapyGenMappings,
) -> String {
    // 1. Name overrides (e.g., src → SourceIPField)
    if let Some(cls) = mappings.name_override(name) {
        return cls.to_string();
    }

    // 2. FlagsField with flag_names
    if *ft == FieldType::Flags && flag_names.is_some() {
        return "FlagsField".to_string();
    }

    // 3. Generic (type, size) mapping
    let base_class = mappings
        .field_class(ft, bits)
        .unwrap_or_else(|| {
            // Fallback for unknown sizes
            if bits <= 8 { "ByteField" }
            else if bits <= 16 { "ShortField" }
            else if bits <= 32 { "IntField" }
            else { "LongField" }
        })
        .to_string();

    // 4. Apply LE prefix if little-endian
    if *endian == Endian::Little {
        if let Some(le) = mappings.le_variant(&base_class) {
            return le.to_string();
        }
    }

    base_class
}

/// Format a Scapy field constructor string.
fn format_scapy_field(
    class: &str,
    name: &str,
    bits: u32,
    ft: &FieldType,
    default: &Option<String>,
    flag_names: &Option<Vec<String>>,
) -> String {
    match class {
        "BitField" => {
            format!(
                "BitField(\"{}\", {}, {})",
                name,
                default.as_deref().unwrap_or("0"),
                bits
            )
        }
        "FlagsField" => {
            if let Some(ref names) = flag_names {
                let names_str: Vec<String> = names.iter().map(|n| format!("\"{}\"", n)).collect();
                format!(
                    "FlagsField(\"{}\", {}, {}, [{}])",
                    name,
                    default.as_deref().unwrap_or("0"),
                    bits,
                    names_str.join(", ")
                )
            } else {
                format!(
                    "FlagsField(\"{}\", {}, {})",
                    name,
                    default.as_deref().unwrap_or("0"),
                    bits
                )
            }
        }
        _ => {
            // Standard field: FieldClass("name", default)
            if let Some(ref d) = default {
                format!("{}(\"{}\", {})", class, name, d)
            } else {
                // Use sensible defaults
                let default_val = match ft {
                    FieldType::Ipv4Addr => "\"0.0.0.0\"",
                    FieldType::Ipv6Addr => "\"::\"",
                    FieldType::MacAddr => "\"00:00:00:00:00:00\"",
                    _ => "0",
                };
                format!("{}(\"{}\", {})", class, name, default_val)
            }
        }
    }
}

/// Format a dispatch value: use hex for values >= 256.
fn format_value(v: u32) -> String {
    if v >= 256 {
        format!("0x{:04x}", v)
    } else {
        v.to_string()
    }
}

/// "IPv4" → "Ipv4", "TCP" → "Tcp", "IEEE802.1Q" → "Ieee8021Q"
fn canonical_to_pascal(name: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for ch in name.chars() {
        if ch == '.' || ch == '-' || ch == '_' || ch == ' ' {
            capitalize_next = true;
            continue;
        }
        if capitalize_next {
            result.push(ch.to_uppercase().next().unwrap_or(ch));
            capitalize_next = false;
        } else {
            result.push(ch.to_lowercase().next().unwrap_or(ch));
        }
    }
    // Special case: keep well-known acronyms
    // Actually, for Scapy we want the original name as class name
    // Return the canonical name directly for Scapy compatibility
    name.replace('.', "").replace('-', "").replace(' ', "")
}

/// Determine smallest Rust integer type for a given bit width.
fn rust_type_for_bits(bits: u32) -> String {
    match bits {
        0..=1 => "bool".to_string(),
        2..=8 => "u8".to_string(),
        9..=16 => "u16".to_string(),
        17..=32 => "u32".to_string(),
        33..=64 => "u64".to_string(),
        _ => "u128".to_string(),
    }
}

/// Convert field name to valid Rust identifier.
fn field_name_rust(name: &str) -> String {
    let name = name
        .to_lowercase()
        .replace('.', "_")
        .replace('-', "_")
        .replace(' ', "_");
    // Avoid Rust keywords
    match name.as_str() {
        "type" => "r#type".to_string(),
        "mod" => "r#mod".to_string(),
        "ref" => "r#ref".to_string(),
        _ => name,
    }
}

/// Check if a field is byte-aligned (both offset and size are multiples of 8).
fn is_byte_aligned(offset_bits: u32, size_bits: u32) -> bool {
    offset_bits % 8 == 0 && size_bits % 8 == 0
}

/// Flush accumulated bitfield entries as a comment + packed field.
fn flush_bitfield_group(out: &mut String, group: &mut Vec<(&str, u32)>) {
    if group.is_empty() {
        return;
    }
    let total_bits: u32 = group.iter().map(|(_, b)| b).sum();
    let rust_type = rust_type_for_bits(total_bits);
    // Emit each sub-field as a doc comment showing bit allocation
    out.push_str("    /// Packed bitfield:\n");
    for (name, bits) in group.iter() {
        out.push_str(&format!("    ///   {} ({} bits)\n", name, bits));
    }
    // Use first field name as the packed field name
    let field_name = group[0].0;
    out.push_str(&format!("    pub {}_raw: {},\n", field_name_rust(field_name), rust_type));
    group.clear();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;
    use std::collections::BTreeMap;

    #[test]
    fn test_generate_leaf_protocol() {
        let proto = ProtocolDef {
            name: "UDP".to_string(),
            min_header_bits: 64,
            is_variable_length: false,
            fields: vec![],
            dispatch_field: Some("dest".to_string()),
            dispatch_table: vec![],
            identifiers: BTreeMap::new(),
            sources: BTreeMap::new(),
        };

        let header = generate_proto_def(&proto);

        assert!(header.contains("#ifndef __XDP2_PROTO_UDP_H__"));
        assert!(header.contains("#define __XDP2_PROTO_UDP_H__"));
        assert!(header.contains("#include <linux/udp.h>"));
        assert!(header.contains("xdp2_parse_udp"));
        assert!(header.contains(".name = \"UDP\""));
        assert!(header.contains("sizeof(struct udphdr)"));
        assert!(header.contains("udp_proto"));
        assert!(!header.contains("ops.len")); // not variable length
    }

    #[test]
    fn test_generate_variable_length() {
        let proto = ProtocolDef {
            name: "IPv4".to_string(),
            min_header_bits: 160,
            is_variable_length: true,
            fields: vec![
                FieldDef {
                    name: "ihl".to_string(),
                    offset_bits: 4,
                    size_bits: 4,
                    field_type: FieldType::Uint,
                    endian: Endian::Na,
                    description: String::new(),
                    is_dispatch: false,
                    is_length: true,
                    length_multiplier: Some(4),
                    source_names: BTreeMap::from([("kernel".into(), "ihl".into())]),
                    default_value: None,
                    flag_names: None,
                },
                FieldDef {
                    name: "protocol".to_string(),
                    offset_bits: 72,
                    size_bits: 8,
                    field_type: FieldType::Enum,
                    endian: Endian::Na,
                    description: String::new(),
                    is_dispatch: true,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("kernel".into(), "protocol".into())]),
                    default_value: None,
                    flag_names: None,
                },
            ],
            dispatch_field: Some("protocol".to_string()),
            dispatch_table: vec![],
            identifiers: BTreeMap::new(),
            sources: BTreeMap::new(),
        };

        let header = generate_proto_def(&proto);

        assert!(header.contains("ipv4_length"));
        assert!(header.contains("ihl * 4"));
        assert!(header.contains(".ops.len = ipv4_length"));
        assert!(header.contains("ipv4_proto"));
        assert!(header.contains(".ops.next_proto = ipv4_proto"));
    }

    #[test]
    fn test_canonical_to_snake() {
        assert_eq!(canonical_to_snake("IPv4"), "ipv4");
        assert_eq!(canonical_to_snake("TCP"), "tcp");
        assert_eq!(canonical_to_snake("IEEE802.11"), "ieee802_11");
        assert_eq!(canonical_to_snake("CAN_FD"), "can_fd");
    }

    /// Build a sample UDP ProtocolDef with all 4 fields for generator tests.
    fn sample_udp() -> ProtocolDef {
        ProtocolDef {
            name: "UDP".to_string(),
            min_header_bits: 64,
            is_variable_length: false,
            fields: vec![
                FieldDef {
                    name: "src_port".to_string(),
                    offset_bits: 0,
                    size_bits: 16,
                    field_type: FieldType::Uint,
                    endian: Endian::Big,
                    description: "Source port".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "sport".into())]),
                    default_value: Some("53".to_string()),
                    flag_names: None,
                },
                FieldDef {
                    name: "dst_port".to_string(),
                    offset_bits: 16,
                    size_bits: 16,
                    field_type: FieldType::Uint,
                    endian: Endian::Big,
                    description: "Destination port".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "dport".into())]),
                    default_value: Some("53".to_string()),
                    flag_names: None,
                },
                FieldDef {
                    name: "length".to_string(),
                    offset_bits: 32,
                    size_bits: 16,
                    field_type: FieldType::Uint,
                    endian: Endian::Big,
                    description: "Datagram length".to_string(),
                    is_dispatch: false,
                    is_length: true,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "len".into())]),
                    default_value: None,
                    flag_names: None,
                },
                FieldDef {
                    name: "checksum".to_string(),
                    offset_bits: 48,
                    size_bits: 16,
                    field_type: FieldType::Uint,
                    endian: Endian::Big,
                    description: "Checksum".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "chksum".into())]),
                    default_value: None,
                    flag_names: None,
                },
            ],
            dispatch_field: None,
            dispatch_table: vec![],
            identifiers: BTreeMap::new(),
            sources: BTreeMap::new(),
        }
    }

    /// Build a sample IPv4-like protocol with mixed field types for testing.
    fn sample_ipv4_rich() -> ProtocolDef {
        ProtocolDef {
            name: "IPv4".to_string(),
            min_header_bits: 160,
            is_variable_length: true,
            fields: vec![
                FieldDef {
                    name: "version".to_string(),
                    offset_bits: 0,
                    size_bits: 4,
                    field_type: FieldType::Uint,
                    endian: Endian::Na,
                    description: "IP version".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "version".into())]),
                    default_value: Some("4".to_string()),
                    flag_names: None,
                },
                FieldDef {
                    name: "ihl".to_string(),
                    offset_bits: 4,
                    size_bits: 4,
                    field_type: FieldType::Uint,
                    endian: Endian::Na,
                    description: "Header length".to_string(),
                    is_dispatch: false,
                    is_length: true,
                    length_multiplier: Some(4),
                    source_names: BTreeMap::from([("scapy".into(), "ihl".into())]),
                    default_value: None,
                    flag_names: None,
                },
                FieldDef {
                    name: "tos".to_string(),
                    offset_bits: 8,
                    size_bits: 8,
                    field_type: FieldType::Uint,
                    endian: Endian::Na,
                    description: String::new(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "tos".into())]),
                    default_value: Some("0".to_string()),
                    flag_names: None,
                },
                FieldDef {
                    name: "total_length".to_string(),
                    offset_bits: 16,
                    size_bits: 16,
                    field_type: FieldType::Uint,
                    endian: Endian::Big,
                    description: String::new(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "len".into())]),
                    default_value: None,
                    flag_names: None,
                },
                FieldDef {
                    name: "flags".to_string(),
                    offset_bits: 48,
                    size_bits: 3,
                    field_type: FieldType::Flags,
                    endian: Endian::Na,
                    description: "IP flags".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "flags".into())]),
                    default_value: None,
                    flag_names: Some(vec!["Reserved".into(), "DF".into(), "MF".into()]),
                },
                FieldDef {
                    name: "protocol".to_string(),
                    offset_bits: 72,
                    size_bits: 8,
                    field_type: FieldType::Enum,
                    endian: Endian::Na,
                    description: "Next protocol".to_string(),
                    is_dispatch: true,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "proto".into())]),
                    default_value: Some("0".to_string()),
                    flag_names: None,
                },
                FieldDef {
                    name: "src_addr".to_string(),
                    offset_bits: 96,
                    size_bits: 32,
                    field_type: FieldType::Ipv4Addr,
                    endian: Endian::Big,
                    description: "Source address".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "src".into())]),
                    default_value: None,
                    flag_names: None,
                },
                FieldDef {
                    name: "dst_addr".to_string(),
                    offset_bits: 128,
                    size_bits: 32,
                    field_type: FieldType::Ipv4Addr,
                    endian: Endian::Big,
                    description: "Destination address".to_string(),
                    is_dispatch: false,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("scapy".into(), "dst".into())]),
                    default_value: None,
                    flag_names: None,
                },
            ],
            dispatch_field: Some("protocol".to_string()),
            dispatch_table: vec![
                DispatchEntry {
                    value: 6,
                    protocol: "TCP".to_string(),
                    sources: vec!["scapy".into()],
                },
                DispatchEntry {
                    value: 17,
                    protocol: "UDP".to_string(),
                    sources: vec!["scapy".into()],
                },
            ],
            identifiers: BTreeMap::new(),
            sources: BTreeMap::new(),
        }
    }

    // ── etherparse generator tests ──

    #[test]
    fn test_generate_etherparse_udp() {
        let proto = sample_udp();
        let output = generate_etherparse(&proto);

        assert!(output.contains("pub struct UDPHeader"));
        assert!(output.contains("pub src_port: u16"));
        assert!(output.contains("pub dst_port: u16"));
        assert!(output.contains("pub length: u16"));
        assert!(output.contains("pub checksum: u16"));
        assert!(output.contains("#[derive(Debug, Clone, PartialEq, Eq)]"));
        assert!(output.contains("MIN_LEN: usize = 8"));
    }

    #[test]
    fn test_generate_etherparse_ipv4() {
        let proto = sample_ipv4_rich();
        let output = generate_etherparse(&proto);

        assert!(output.contains("pub struct IPv4Header"));
        // IPv4 addresses should be [u8; 4]
        assert!(output.contains("[u8; 4]"));
        // Protocol field should use IpNumber newtype
        assert!(output.contains("pub protocol: IpNumber"));
        assert!(output.contains("MIN_LEN: usize = 20"));
    }

    #[test]
    fn test_generate_etherparse_has_impl() {
        let proto = sample_udp();
        let output = generate_etherparse(&proto);

        assert!(output.contains("impl UDPHeader"));
        assert!(output.contains("from_slice"));
    }

    // ── Scapy generator tests ──

    #[test]
    fn test_generate_scapy_udp() {
        let proto = sample_udp();
        let output = generate_scapy(&proto);

        assert!(output.contains("class UDP(Packet)"));
        assert!(output.contains("name = \"UDP\""));
        assert!(output.contains("fields_desc = ["));
        // sport has a default of "53"
        assert!(output.contains("\"sport\", 53"));
        // chksum should use XShortField (name override)
        assert!(output.contains("XShortField(\"chksum\""));
    }

    #[test]
    fn test_generate_scapy_ipv4() {
        let proto = sample_ipv4_rich();
        let output = generate_scapy(&proto);

        assert!(output.contains("class IPv4(Packet)"));
        // BitField for sub-byte
        assert!(output.contains("BitField(\"version\", 4, 4)"));
        // FlagsField with flag names
        assert!(output.contains("FlagsField(\"flags\""));
        assert!(output.contains("\"Reserved\""));
        assert!(output.contains("\"DF\""));
        assert!(output.contains("\"MF\""));
        // IP addresses
        assert!(output.contains("SourceIPField(\"src\""));
        assert!(output.contains("DestIPField(\"dst\""));
        // Enum field
        assert!(output.contains("ByteEnumField(\"proto\""));
    }

    #[test]
    fn test_generate_scapy_bind_layers() {
        let proto = sample_ipv4_rich();
        let output = generate_scapy(&proto);

        assert!(output.contains("bind_layers(IPv4, TCP, proto=6)"));
        assert!(output.contains("bind_layers(IPv4, UDP, proto=17)"));
    }

    #[test]
    fn test_generate_scapy_imports() {
        let proto = sample_udp();
        let output = generate_scapy(&proto);

        assert!(output.contains("from scapy.packet import Packet, bind_layers"));
        assert!(output.contains("from scapy.fields import *"));
    }

    // ── Helper function tests ──

    #[test]
    fn test_canonical_to_pascal() {
        assert_eq!(canonical_to_pascal("IPv4"), "IPv4");
        assert_eq!(canonical_to_pascal("TCP"), "TCP");
        assert_eq!(canonical_to_pascal("IEEE802.1Q"), "IEEE8021Q");
    }

    #[test]
    fn test_rust_type_for_bits() {
        assert_eq!(rust_type_for_bits(1), "bool");
        assert_eq!(rust_type_for_bits(8), "u8");
        assert_eq!(rust_type_for_bits(16), "u16");
        assert_eq!(rust_type_for_bits(32), "u32");
        assert_eq!(rust_type_for_bits(64), "u64");
    }

    #[test]
    fn test_field_name_rust() {
        assert_eq!(field_name_rust("type"), "r#type");
        assert_eq!(field_name_rust("src_addr"), "src_addr");
        assert_eq!(field_name_rust("Total-Length"), "total_length");
    }

    #[test]
    fn test_etherparse_gen_mappings_load() {
        let m = type_mapping::load_etherparse_gen_mappings(None).unwrap();
        assert_eq!(m.rust_type(&FieldType::Uint, 16), Some("u16"));
        assert_eq!(m.rust_type(&FieldType::Ipv4Addr, 32), Some("[u8; 4]"));
        assert_eq!(m.rust_type(&FieldType::MacAddr, 48), Some("[u8; 6]"));
        assert_eq!(m.newtype("protocol"), Some("IpNumber"));
        assert_eq!(m.newtype("ether_type"), Some("EtherType"));
    }

    #[test]
    fn test_scapy_gen_mappings_load() {
        let m = type_mapping::load_scapy_gen_mappings(None).unwrap();
        assert_eq!(m.field_class(&FieldType::Uint, 8), Some("ByteField"));
        assert_eq!(m.field_class(&FieldType::Uint, 16), Some("ShortField"));
        assert_eq!(m.field_class(&FieldType::Ipv4Addr, 32), Some("IPField"));
        assert_eq!(m.field_class(&FieldType::Flags, 3), Some("FlagsField"));
        assert_eq!(m.name_override("src"), Some("SourceIPField"));
        assert_eq!(m.le_variant("ShortField"), Some("LEShortField"));
    }
}
