//! C header generator: IR ProtocolDef → XDP2 proto_def header.
//!
//! Generates a complete proto_def .h file from an IR ProtocolDef,
//! following the XDP2 proto_def conventions:
//! - SPDX header
//! - Include guard
//! - Kernel struct include
//! - Helper functions (len, proto)
//! - Conditional proto_def struct

use crate::ir::ProtocolDef;
use crate::name_mapping;

/// Generate a complete XDP2 proto_def C header from a ProtocolDef.
pub fn generate_proto_def(proto: &ProtocolDef) -> String {
    let canonical = &proto.name;

    // Look up names from the mapping table
    let names = name_mapping::find_by_canonical(canonical);

    let snake = canonical_to_snake(canonical);
    let upper = canonical_to_upper(canonical);
    let guard = format!("__XDP2_PROTO_{}_H__", upper);

    let kernel_header = names
        .as_ref()
        .and_then(|n| n.kernel_header)
        .unwrap_or("linux/types.h");

    let kernel_struct = names
        .as_ref()
        .and_then(|n| n.kernel_struct)
        .unwrap_or("unknown_hdr");

    let has_next_proto = proto.dispatch_field.is_some();
    let has_variable_len = proto.is_variable_length;

    let mut out = String::new();

    // SPDX + license header
    out.push_str(&format!(
        "/* SPDX-License-Identifier: BSD-2-Clause-FreeBSD\n\
         *\n\
         * Auto-generated by proto-audit from IR definition.\n\
         * Protocol: {}\n\
         */\n\n",
        canonical
    ));

    // Include guard
    out.push_str(&format!("#ifndef {}\n", guard));
    out.push_str(&format!("#define {}\n\n", guard));

    // Includes
    out.push_str(&format!("#include <{}>\n\n", kernel_header));
    out.push_str("#include \"xdp2/parser.h\"\n\n");

    // Helper: next_proto function
    if has_next_proto {
        if let Some(ref dispatch_field) = proto.dispatch_field {
            // Find the actual kernel field name for the dispatch field
            let kernel_field = proto
                .fields
                .iter()
                .find(|f| &f.name == dispatch_field)
                .and_then(|f| f.source_names.get("kernel"))
                .map(|s| s.as_str())
                .unwrap_or(dispatch_field.as_str());

            out.push_str(&format!(
                "static inline int {}_proto(const void *vhdr)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{};\n\
                 }}\n\n",
                snake, kernel_struct, kernel_field
            ));
        }
    }

    // Helper: variable length function
    if has_variable_len {
        // Find the length field
        let len_field = proto.fields.iter().find(|f| f.is_length);

        if let Some(lf) = len_field {
            let kernel_field = lf
                .source_names
                .get("kernel")
                .map(|s| s.as_str())
                .unwrap_or(&lf.name);

            let multiplier = lf.length_multiplier.unwrap_or(1);

            out.push_str(&format!(
                "static inline ssize_t {}_length(const void *vhdr, size_t maxlen)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{}{};  \n\
                 }}\n\n",
                snake,
                kernel_struct,
                kernel_field,
                if multiplier > 1 {
                    format!(" * {}", multiplier)
                } else {
                    String::new()
                }
            ));
        }
    }

    // End of regular header section
    out.push_str(&format!("#endif /* {} */\n\n", guard));

    // Conditional proto_def struct
    out.push_str("#ifdef XDP2_DEFINE_PARSE_NODE\n\n");

    // Proto_def comment
    out.push_str(&format!(
        "/* xdp2_parse_{} protocol definition\n\
         *\n\
         * Parse {} header\n",
        snake, canonical
    ));
    if has_next_proto {
        out.push_str(" *\n * Next protocol operation returns protocol identifier\n");
    }
    out.push_str(" */\n");

    // Proto_def struct
    out.push_str(&format!(
        "static const struct xdp2_proto_def xdp2_parse_{} __unused() = {{\n",
        snake
    ));
    out.push_str(&format!("\t.name = \"{}\",\n", canonical));
    out.push_str(&format!(
        "\t.min_len = sizeof(struct {}),\n",
        kernel_struct
    ));
    if has_variable_len {
        out.push_str(&format!("\t.ops.len = {}_length,\n", snake));
    }
    if has_next_proto {
        out.push_str(&format!("\t.ops.next_proto = {}_proto,\n", snake));
    }
    out.push_str("};\n\n");

    out.push_str("#endif /* XDP2_DEFINE_PARSE_NODE */\n");

    out
}

/// Convert "IPv4" → "ipv4", "TCP" → "tcp", "IEEE802.11" → "ieee802_11"
fn canonical_to_snake(name: &str) -> String {
    name.to_lowercase()
        .replace('.', "_")
        .replace('-', "_")
        .replace(' ', "_")
}

/// Convert "IPv4" → "IPV4", "TCP" → "TCP"
fn canonical_to_upper(name: &str) -> String {
    name.to_uppercase()
        .replace('.', "_")
        .replace('-', "_")
        .replace(' ', "_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;
    use std::collections::BTreeMap;

    #[test]
    fn test_generate_leaf_protocol() {
        let proto = ProtocolDef {
            name: "UDP".to_string(),
            min_header_bits: 64,
            is_variable_length: false,
            fields: vec![],
            dispatch_field: Some("dest".to_string()),
            dispatch_table: vec![],
            identifiers: BTreeMap::new(),
            sources: BTreeMap::new(),
        };

        let header = generate_proto_def(&proto);

        assert!(header.contains("#ifndef __XDP2_PROTO_UDP_H__"));
        assert!(header.contains("#define __XDP2_PROTO_UDP_H__"));
        assert!(header.contains("#include <linux/udp.h>"));
        assert!(header.contains("xdp2_parse_udp"));
        assert!(header.contains(".name = \"UDP\""));
        assert!(header.contains("sizeof(struct udphdr)"));
        assert!(header.contains("udp_proto"));
        assert!(!header.contains("ops.len")); // not variable length
    }

    #[test]
    fn test_generate_variable_length() {
        let proto = ProtocolDef {
            name: "IPv4".to_string(),
            min_header_bits: 160,
            is_variable_length: true,
            fields: vec![
                FieldDef {
                    name: "ihl".to_string(),
                    offset_bits: 4,
                    size_bits: 4,
                    field_type: FieldType::Uint,
                    endian: Endian::Na,
                    description: String::new(),
                    is_dispatch: false,
                    is_length: true,
                    length_multiplier: Some(4),
                    source_names: BTreeMap::from([("kernel".into(), "ihl".into())]),
                },
                FieldDef {
                    name: "protocol".to_string(),
                    offset_bits: 72,
                    size_bits: 8,
                    field_type: FieldType::Enum,
                    endian: Endian::Na,
                    description: String::new(),
                    is_dispatch: true,
                    is_length: false,
                    length_multiplier: None,
                    source_names: BTreeMap::from([("kernel".into(), "protocol".into())]),
                },
            ],
            dispatch_field: Some("protocol".to_string()),
            dispatch_table: vec![],
            identifiers: BTreeMap::new(),
            sources: BTreeMap::new(),
        };

        let header = generate_proto_def(&proto);

        assert!(header.contains("ipv4_length"));
        assert!(header.contains("ihl * 4"));
        assert!(header.contains(".ops.len = ipv4_length"));
        assert!(header.contains("ipv4_proto"));
        assert!(header.contains(".ops.next_proto = ipv4_proto"));
    }

    #[test]
    fn test_canonical_to_snake() {
        assert_eq!(canonical_to_snake("IPv4"), "ipv4");
        assert_eq!(canonical_to_snake("TCP"), "tcp");
        assert_eq!(canonical_to_snake("IEEE802.11"), "ieee802_11");
        assert_eq!(canonical_to_snake("CAN_FD"), "can_fd");
    }
}
