use crate::ir::ProtocolDef;
use crate::name_mapping;

use super::{canonical_to_snake, canonical_to_upper};

/// Generate a complete XDP2 proto_def C header using explicit kernel names.
/// Used for discovered protocols that have kernel struct matches but aren't curated.
pub fn generate_proto_def_with_names(
    proto: &ProtocolDef,
    kernel_struct: &str,
    kernel_header: &str,
) -> String {
    generate_proto_def_inner(proto, kernel_struct, kernel_header)
}

/// Generate a complete XDP2 proto_def C header from a ProtocolDef.
pub fn generate_proto_def(proto: &ProtocolDef) -> String {
    let canonical = &proto.name;

    // Look up names from the mapping table
    let names = name_mapping::find_by_canonical(canonical);

    let kernel_header = names
        .as_ref()
        .and_then(|n| n.kernel_header)
        .unwrap_or("linux/types.h");

    let kernel_struct = names
        .as_ref()
        .and_then(|n| n.kernel_struct)
        .unwrap_or("unknown_hdr");

    generate_proto_def_inner(proto, kernel_struct, kernel_header)
}

fn generate_proto_def_inner(proto: &ProtocolDef, kernel_struct: &str, kernel_header: &str) -> String {
    let canonical = &proto.name;

    let snake = canonical_to_snake(canonical);
    let upper = canonical_to_upper(canonical);
    let guard = format!("__XDP2_PROTO_{}_H__", upper);

    let has_next_proto = proto.dispatch_field.is_some();
    let has_variable_len = proto.is_variable_length;

    let mut out = String::new();

    // SPDX + license header
    out.push_str(&format!(
        "/* SPDX-License-Identifier: BSD-2-Clause-FreeBSD\n\
         *\n\
         * Auto-generated by proto-audit from IR definition.\n\
         * Protocol: {}\n\
         */\n\n",
        canonical
    ));

    // Include guard
    out.push_str(&format!("#ifndef {}\n", guard));
    out.push_str(&format!("#define {}\n\n", guard));

    // Includes
    out.push_str(&format!("#include <{}>\n\n", kernel_header));
    out.push_str("#include \"xdp2/parser.h\"\n\n");

    // Helper: next_proto function
    if has_next_proto {
        if let Some(ref dispatch_field) = proto.dispatch_field {
            let kernel_field = proto
                .fields
                .iter()
                .find(|f| &f.name == dispatch_field)
                .and_then(|f| f.source_names.get("kernel"))
                .map(|s| s.as_str())
                .unwrap_or(dispatch_field.as_str());

            out.push_str(&format!(
                "static inline int {}_proto(const void *vhdr)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{};\n\
                 }}\n\n",
                snake, kernel_struct, kernel_field
            ));
        }
    }

    // Helper: variable length function
    if has_variable_len {
        let len_field = proto.fields.iter().find(|f| f.is_length);

        if let Some(lf) = len_field {
            let kernel_field = lf
                .source_names
                .get("kernel")
                .map(|s| s.as_str())
                .unwrap_or(&lf.name);

            let multiplier = lf.length_multiplier.unwrap_or(1);

            out.push_str(&format!(
                "static inline ssize_t {}_length(const void *vhdr, size_t maxlen)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{}{};  \n\
                 }}\n\n",
                snake,
                kernel_struct,
                kernel_field,
                if multiplier > 1 {
                    format!(" * {}", multiplier)
                } else {
                    String::new()
                }
            ));
        }
    }

    // End of regular header section
    out.push_str(&format!("#endif /* {} */\n\n", guard));

    // Conditional proto_def struct
    out.push_str("#ifdef XDP2_DEFINE_PARSE_NODE\n\n");

    // Proto_def comment
    out.push_str(&format!(
        "/* xdp2_parse_{} protocol definition\n\
         *\n\
         * Parse {} header\n",
        snake, canonical
    ));
    if has_next_proto {
        out.push_str(" *\n * Next protocol operation returns protocol identifier\n");
    }
    out.push_str(" */\n");

    // Proto_def struct
    out.push_str(&format!(
        "static const struct xdp2_proto_def xdp2_parse_{} __unused() = {{\n",
        snake
    ));
    out.push_str(&format!("\t.name = \"{}\",\n", canonical));
    out.push_str(&format!(
        "\t.min_len = sizeof(struct {}),\n",
        kernel_struct
    ));
    if has_variable_len {
        out.push_str(&format!("\t.ops.len = {}_length,\n", snake));
    }
    if has_next_proto {
        out.push_str(&format!("\t.ops.next_proto = {}_proto,\n", snake));
    }
    out.push_str("};\n\n");

    out.push_str("#endif /* XDP2_DEFINE_PARSE_NODE */\n");

    out
}

/// Generate a synthetic packed struct from IR fields for protocols without a kernel UAPI struct.
///
/// Used for discovered protocols that have extractable fields but no matching kernel header.
/// The struct uses `__beNN`/`uint8_t` types and `__attribute__((packed))` for BPF compatibility.
pub fn generate_proto_def_synthetic(proto: &ProtocolDef) -> String {
    let canonical = &proto.name;
    let snake = canonical_to_snake(canonical);
    let upper = canonical_to_upper(canonical);
    let guard = format!("__XDP2_PROTO_{}_H__", upper);
    let struct_name = format!("proto_audit_{}_hdr", snake);

    let has_next_proto = proto.dispatch_field.is_some();
    let has_variable_len = proto.is_variable_length;

    let mut out = String::new();

    // SPDX + header
    out.push_str(&format!(
        "/* SPDX-License-Identifier: BSD-2-Clause-FreeBSD\n\
         *\n\
         * Auto-generated by proto-audit from IR definition.\n\
         * Protocol: {} (synthetic struct — no kernel UAPI match)\n\
         */\n\n",
        canonical
    ));

    out.push_str(&format!("#ifndef {}\n", guard));
    out.push_str(&format!("#define {}\n\n", guard));

    // Includes for types
    out.push_str("#include <linux/types.h>\n");
    out.push_str("#include \"xdp2/parser.h\"\n\n");

    // Generate synthetic packed struct from IR fields
    out.push_str(&format!(
        "/* Synthetic struct from proto-audit IR */\n\
         struct {} __attribute__((packed)) {{\n",
        struct_name
    ));

    // Only emit byte-aligned fields
    let mut current_bit = 0u32;
    for field in &proto.fields {
        // Skip sub-byte fields that aren't byte-aligned
        if field.offset_bits != current_bit {
            // Insert padding if there's a gap
            let gap = field.offset_bits.saturating_sub(current_bit);
            if gap > 0 && gap % 8 == 0 {
                let gap_bytes = gap / 8;
                out.push_str(&format!("\t__u8 _pad_{}[{}];\n", current_bit / 8, gap_bytes));
            } else if gap > 0 {
                // Non-byte-aligned gap, skip to next byte boundary
            }
        }

        let c_type = ir_field_to_c_type(field);
        let field_name = canonical_to_snake(&field.name);
        out.push_str(&format!("\t{} {};\n", c_type, field_name));
        current_bit = field.offset_bits + field.size_bits;
    }

    out.push_str("};\n\n");

    // Helper functions
    if has_next_proto {
        if let Some(ref dispatch_field) = proto.dispatch_field {
            let field_name = canonical_to_snake(dispatch_field);
            out.push_str(&format!(
                "static inline int {}_proto(const void *vhdr)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{};\n\
                 }}\n\n",
                snake, struct_name, field_name
            ));
        }
    }

    if has_variable_len {
        let len_field = proto.fields.iter().find(|f| f.is_length);
        if let Some(lf) = len_field {
            let field_name = canonical_to_snake(&lf.name);
            let multiplier = lf.length_multiplier.unwrap_or(1);
            out.push_str(&format!(
                "static inline ssize_t {}_length(const void *vhdr, size_t maxlen)\n\
                 {{\n\
                 \treturn ((struct {} *)vhdr)->{}{};  \n\
                 }}\n\n",
                snake,
                struct_name,
                field_name,
                if multiplier > 1 {
                    format!(" * {}", multiplier)
                } else {
                    String::new()
                }
            ));
        }
    }

    out.push_str(&format!("#endif /* {} */\n\n", guard));

    // Proto_def struct
    out.push_str("#ifdef XDP2_DEFINE_PARSE_NODE\n\n");
    out.push_str(&format!(
        "static const struct xdp2_proto_def xdp2_parse_{} __unused() = {{\n",
        snake
    ));
    out.push_str(&format!("\t.name = \"{}\",\n", canonical));
    out.push_str(&format!(
        "\t.min_len = sizeof(struct {}),\n",
        struct_name
    ));
    if has_variable_len {
        out.push_str(&format!("\t.ops.len = {}_length,\n", snake));
    }
    if has_next_proto {
        out.push_str(&format!("\t.ops.next_proto = {}_proto,\n", snake));
    }
    out.push_str("};\n\n");
    out.push_str("#endif /* XDP2_DEFINE_PARSE_NODE */\n");

    out
}

/// Generate a libpcap overlay patch from an IR definition.
///
/// Produces a unified diff that creates `pcap/proto_audit/<name>.h` with a
/// packed C struct suitable for cross-source comparison. Fields use stdint
/// types (uint8_t, uint16_t, etc.) rather than kernel __beNN types.
pub fn generate_libpcap_patch(proto: &ProtocolDef) -> Option<String> {
    let fields = &proto.fields;
    if fields.is_empty() {
        return None;
    }

    let snake = canonical_to_snake(&proto.name);
    let upper = canonical_to_upper(&proto.name);
    let guard = format!("PROTO_AUDIT_{}_H", upper);
    let struct_name = format!("{}_header", snake);
    let file_path = format!("pcap/proto_audit/{}.h", snake);
    let min_bytes = proto.min_header_bits / 8;

    // Build struct body — only byte-aligned fields, skip sub-byte bitfields
    let mut body_lines: Vec<String> = Vec::new();
    let mut current_bit = 0u32;

    for field in fields {
        // Skip fields that aren't at expected offset (sub-fields, options)
        if field.offset_bits < current_bit {
            continue;
        }

        // Skip non-byte-aligned fields
        if field.offset_bits % 8 != 0 || field.size_bits % 8 != 0 {
            // Pack sub-byte fields into a combined uint8_t if they fill a byte
            if field.offset_bits == current_bit && field.size_bits < 8 {
                // Accumulate sub-byte fields into one byte
                let byte_start = current_bit;
                let mut sub_fields: Vec<&crate::ir::FieldDef> = vec![field];
                let mut bits_acc = field.size_bits;
                // Look ahead for more sub-fields in the same byte
                for next in fields.iter() {
                    if next.offset_bits == byte_start + bits_acc && bits_acc + next.size_bits <= 8 {
                        sub_fields.push(next);
                        bits_acc += next.size_bits;
                    }
                }
                if bits_acc == 8 {
                    let comment = sub_fields.iter()
                        .map(|f| format!("{}({})", f.name.split('.').last().unwrap_or(&f.name), f.size_bits))
                        .collect::<Vec<_>>()
                        .join("+");
                    let combined_name = format!("{}_{}", snake,
                        sub_fields.first().map(|f| {
                            let n = canonical_to_snake(&f.name);
                            n.split('.').last().unwrap_or(&n).to_string()
                        }).unwrap_or_else(|| format!("byte_{}", byte_start / 8)));
                    body_lines.push(format!("    uint8_t  {:<20} /* {} */", format!("{};", combined_name), comment));
                    current_bit = byte_start + 8;
                    continue;
                }
            }
            continue;
        }

        // Insert padding for gaps
        if field.offset_bits > current_bit {
            let gap = field.offset_bits - current_bit;
            if gap % 8 == 0 {
                let gap_bytes = gap / 8;
                body_lines.push(format!("    uint8_t  _pad{}[{}];", current_bit / 8, gap_bytes));
            }
        }

        let c_type = ir_field_to_stdint(field);
        let field_name = format!("{}_{}", snake, field.name.split('.').last().unwrap_or(&field.name));
        let field_name = canonical_to_snake(&field_name);

        if field.size_bits > 64 {
            // Large fields become byte arrays
            let n_bytes = field.size_bits / 8;
            body_lines.push(format!("    uint8_t  {}[{}];", field_name, n_bytes));
        } else {
            body_lines.push(format!("    {:<8} {};", c_type, field_name));
        }

        current_bit = field.offset_bits + field.size_bits;
    }

    if body_lines.is_empty() {
        return None;
    }

    // Build the header file content
    let mut header = String::new();
    header.push_str(&format!("/*\n * {}.h — {} for proto-audit comparison.\n */\n\n", snake, struct_name));
    header.push_str(&format!("#ifndef {}\n#define {}\n\n", guard, guard));
    header.push_str("#include <stdint.h>\n\n");
    header.push_str(&format!("/* {} header — {} bytes minimum */\n", proto.name, min_bytes));
    header.push_str(&format!("struct {} {{\n", struct_name));
    for line in &body_lines {
        header.push_str(line);
        header.push('\n');
    }
    header.push_str("};\n\n");
    header.push_str(&format!("#endif /* {} */\n", guard));

    // Count lines in the header
    let line_count = header.lines().count();

    // Build the patch
    let mut patch = String::new();
    patch.push_str("--- /dev/null\n");
    patch.push_str(&format!("+++ b/{}\n", file_path));
    patch.push_str(&format!("@@ -0,0 +1,{} @@\n", line_count));
    for line in header.lines() {
        patch.push('+');
        patch.push_str(line);
        patch.push('\n');
    }

    Some(patch)
}

/// Generate a libpcap.toml struct_protocols entry for a protocol.
pub fn generate_libpcap_toml_entry(proto: &ProtocolDef) -> Option<String> {
    let snake = canonical_to_snake(&proto.name);
    let struct_name = format!("{}_header", snake);
    let file_path = format!("pcap/proto_audit/{}.h", snake);

    if proto.fields.is_empty() {
        return None;
    }

    let mut entry = String::new();
    entry.push_str(&format!("[struct_protocols.{}]\n", struct_name));
    entry.push_str(&format!("file = \"{}\"\n", file_path));
    entry.push_str(&format!("struct_name = \"{}\"\n", struct_name));
    entry.push_str(&format!("prefix = \"{}_\"\n", snake));

    Some(entry)
}

/// Map an IR field to a stdint type (for libpcap patches).
fn ir_field_to_stdint(field: &crate::ir::FieldDef) -> &'static str {
    match field.size_bits {
        8 => "uint8_t",
        16 => "uint16_t",
        32 => "uint32_t",
        64 => "uint64_t",
        _ => "uint8_t",
    }
}

/// Map an IR field to a C type string.
fn ir_field_to_c_type(field: &crate::ir::FieldDef) -> &'static str {
    use crate::ir::Endian;
    match field.size_bits {
        8 => "__u8",
        16 => match field.endian {
            Endian::Big => "__be16",
            Endian::Little => "__le16",
            _ => "__be16",
        },
        32 => match field.endian {
            Endian::Big => "__be32",
            Endian::Little => "__le32",
            _ => "__be32",
        },
        64 => match field.endian {
            Endian::Big => "__be64",
            Endian::Little => "__le64",
            _ => "__be64",
        },
        _ => "__u8",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    #[test]
    fn test_generate_leaf_protocol() {
        let proto = ProtocolDef::new("UDP", 64)
            .with_dispatch_field("dest");

        let header = generate_proto_def(&proto);

        assert!(header.contains("#ifndef __XDP2_PROTO_UDP_H__"));
        assert!(header.contains("#define __XDP2_PROTO_UDP_H__"));
        assert!(header.contains("#include <linux/udp.h>"));
        assert!(header.contains("xdp2_parse_udp"));
        assert!(header.contains(".name = \"UDP\""));
        assert!(header.contains("sizeof(struct udphdr)"));
        assert!(header.contains("udp_proto"));
        assert!(!header.contains("ops.len")); // not variable length
    }

    #[test]
    fn test_generate_variable_length() {
        let proto = ProtocolDef::new("IPv4", 160)
            .with_variable_length()
            .with_dispatch_field("protocol")
            .with_fields(vec![
                FieldDef::new("ihl", 4, 4, FieldType::Uint)
                    .with_length(Some(4))
                    .with_source_name("kernel", "ihl"),
                FieldDef::new("protocol", 72, 8, FieldType::Enum)
                    .with_dispatch()
                    .with_source_name("kernel", "protocol"),
            ]);

        let header = generate_proto_def(&proto);

        assert!(header.contains("ipv4_length"));
        assert!(header.contains("ihl * 4"));
        assert!(header.contains(".ops.len = ipv4_length"));
        assert!(header.contains("ipv4_proto"));
        assert!(header.contains(".ops.next_proto = ipv4_proto"));
    }

    #[test]
    fn test_generate_synthetic_struct() {
        let proto = ProtocolDef::new("MQTT", 16)
            .with_fields(vec![
                FieldDef::new("type_flags", 0, 8, FieldType::Uint),
                FieldDef::new("remaining_len", 8, 8, FieldType::Uint),
            ]);

        let header = generate_proto_def_synthetic(&proto);

        assert!(header.contains("synthetic struct"));
        assert!(header.contains("struct proto_audit_mqtt_hdr"));
        assert!(header.contains("__attribute__((packed))"));
        assert!(header.contains("__u8 type_flags"));
        assert!(header.contains("__u8 remaining_len"));
        assert!(header.contains("sizeof(struct proto_audit_mqtt_hdr)"));
        assert!(header.contains("#include <linux/types.h>"));
    }

    #[test]
    fn test_synthetic_with_be16_fields() {
        let proto = ProtocolDef::new("GRE", 32)
            .with_dispatch_field("protocol_type")
            .with_fields(vec![
                FieldDef::new("flags", 0, 16, FieldType::Uint)
                    .with_endian(Endian::Big),
                FieldDef::new("protocol_type", 16, 16, FieldType::Enum)
                    .with_endian(Endian::Big)
                    .with_dispatch(),
            ]);

        let header = generate_proto_def_synthetic(&proto);

        assert!(header.contains("__be16 flags"));
        assert!(header.contains("__be16 protocol_type"));
        assert!(header.contains("gre_proto"));
    }
}
