use crate::ir::{FieldType, ProtocolDef};
use crate::type_mapping;

use super::{canonical_to_pascal, canonical_to_snake, field_name_rust, flush_bitfield_group,
            is_byte_aligned, rust_type_for_bits};

/// Generate a Rust struct definition for etherparse from a ProtocolDef.
pub fn generate_etherparse(proto: &ProtocolDef) -> String {
    let mappings = type_mapping::load_etherparse_gen_mappings(None)
        .expect("embedded etherparse_gen mappings should always parse");

    let struct_name = canonical_to_pascal(&proto.name);
    let snake = canonical_to_snake(&proto.name);

    let mut out = String::new();

    // Header comment
    out.push_str(&format!(
        "// Auto-generated by proto-audit from IR definition.\n\
         // Protocol: {}\n\
         // Minimum header: {} bytes\n\n",
        proto.name,
        proto.min_header_bits / 8
    ));

    // Derives
    let derives = if mappings.derives.default.is_empty() {
        vec![
            "Debug".to_string(),
            "Clone".to_string(),
            "PartialEq".to_string(),
            "Eq".to_string(),
        ]
    } else {
        mappings.derives.default.clone()
    };
    out.push_str(&format!("#[derive({})]\n", derives.join(", ")));

    // Struct definition
    out.push_str(&format!("pub struct {}Header {{\n", struct_name));

    let mut bitfield_group: Vec<(&str, u32)> = Vec::new();

    for field in &proto.fields {
        // Skip fields that etherparse typically omits
        if mappings.should_skip(&format!("{}Header", struct_name), &field.name) {
            continue;
        }

        // Check for newtype override first, then generic type mapping
        let rust_type = if let Some(nt) = mappings.newtype(&field.name) {
            nt.to_string()
        } else if let Some(rt) = mappings.rust_type(&field.field_type, field.size_bits) {
            rt.to_string()
        } else {
            // Fallback: pick smallest Rust integer that fits
            rust_type_for_bits(field.size_bits)
        };

        // Handle single-bit flags as bool fields
        if field.field_type == FieldType::Flags && field.size_bits == 1 {
            out.push_str(&format!("    pub {}: bool,\n", field.name));
            continue;
        }

        // Handle multi-bit sub-byte fields: group contiguous bitfields
        if field.size_bits < 8 && !is_byte_aligned(field.offset_bits, field.size_bits) {
            bitfield_group.push((&field.name, field.size_bits));
            continue;
        }

        // Flush any pending bitfield group
        flush_bitfield_group(&mut out, &mut bitfield_group);

        // Doc comment with description
        if !field.description.is_empty() {
            out.push_str(&format!("    /// {}\n", field.description));
        }

        out.push_str(&format!("    pub {}: {},\n", field_name_rust(&field.name), rust_type));
    }

    // Flush any remaining bitfield group
    flush_bitfield_group(&mut out, &mut bitfield_group);

    out.push_str("}\n\n");

    // Size assertion
    let min_bytes = proto.min_header_bits / 8;
    out.push_str(&format!(
        "// Wire format: {} bytes minimum\n",
        min_bytes
    ));

    // impl block with from_bytes / to_bytes skeleton
    out.push_str(&format!("impl {}Header {{\n", struct_name));
    out.push_str(&format!("    /// Minimum header size in bytes.\n"));
    out.push_str(&format!("    pub const MIN_LEN: usize = {};\n\n", min_bytes));
    out.push_str(&format!("    /// Read from a byte slice.\n"));
    out.push_str(&format!(
        "    pub fn from_slice(slice: &[u8]) -> Result<{}Header, err::LenError> {{\n",
        struct_name
    ));
    out.push_str("        if slice.len() < Self::MIN_LEN {\n");
    out.push_str("            return Err(err::LenError {\n");
    out.push_str("                required_len: Self::MIN_LEN,\n");
    out.push_str("                len: slice.len(),\n");
    out.push_str("                len_source: err::LenSource::Slice,\n");
    out.push_str(&format!("                layer: err::Layer::{},\n", snake));
    out.push_str("                layer_start_offset: 0,\n");
    out.push_str("            });\n");
    out.push_str("        }\n");
    out.push_str(&format!(
        "        todo!(\"parse {} fields from slice\")\n",
        struct_name
    ));
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn sample_udp() -> ProtocolDef {
        ProtocolDef::new("UDP", 64).with_fields(vec![
            FieldDef::new("src_port", 0, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Source port")
                .with_source_name("scapy", "sport").with_default_value("53"),
            FieldDef::new("dst_port", 16, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Destination port")
                .with_source_name("scapy", "dport").with_default_value("53"),
            FieldDef::new("length", 32, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Datagram length")
                .with_length(None).with_source_name("scapy", "len"),
            FieldDef::new("checksum", 48, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Checksum")
                .with_source_name("scapy", "chksum"),
        ])
    }

    fn sample_ipv4_rich() -> ProtocolDef {
        ProtocolDef::new("IPv4", 160)
            .with_variable_length()
            .with_dispatch_field("protocol")
            .with_fields(vec![
                FieldDef::new("version", 0, 4, FieldType::Uint)
                    .with_description("IP version")
                    .with_source_name("scapy", "version").with_default_value("4"),
                FieldDef::new("ihl", 4, 4, FieldType::Uint)
                    .with_description("Header length")
                    .with_length(Some(4)).with_source_name("scapy", "ihl"),
                FieldDef::new("tos", 8, 8, FieldType::Uint)
                    .with_source_name("scapy", "tos").with_default_value("0"),
                FieldDef::new("total_length", 16, 16, FieldType::Uint)
                    .with_endian(Endian::Big).with_source_name("scapy", "len"),
                FieldDef::new("flags", 48, 3, FieldType::Flags)
                    .with_description("IP flags")
                    .with_source_name("scapy", "flags")
                    .with_flag_names(vec!["Reserved".into(), "DF".into(), "MF".into()]),
                FieldDef::new("protocol", 72, 8, FieldType::Enum)
                    .with_description("Next protocol").with_dispatch()
                    .with_source_name("scapy", "proto").with_default_value("0"),
                FieldDef::new("src_addr", 96, 32, FieldType::Ipv4Addr)
                    .with_endian(Endian::Big).with_description("Source address")
                    .with_source_name("scapy", "src"),
                FieldDef::new("dst_addr", 128, 32, FieldType::Ipv4Addr)
                    .with_endian(Endian::Big).with_description("Destination address")
                    .with_source_name("scapy", "dst"),
            ])
    }

    #[test]
    fn test_generate_etherparse_udp() {
        let proto = sample_udp();
        let output = generate_etherparse(&proto);

        assert!(output.contains("pub struct UDPHeader"));
        assert!(output.contains("pub src_port: u16"));
        assert!(output.contains("pub dst_port: u16"));
        assert!(output.contains("pub length: u16"));
        assert!(output.contains("pub checksum: u16"));
        assert!(output.contains("#[derive(Debug, Clone, PartialEq, Eq)]"));
        assert!(output.contains("MIN_LEN: usize = 8"));
    }

    #[test]
    fn test_generate_etherparse_ipv4() {
        let proto = sample_ipv4_rich();
        let output = generate_etherparse(&proto);

        assert!(output.contains("pub struct IPv4Header"));
        assert!(output.contains("[u8; 4]"));
        assert!(output.contains("pub protocol: IpNumber"));
        assert!(output.contains("MIN_LEN: usize = 20"));
    }

    #[test]
    fn test_generate_etherparse_has_impl() {
        let proto = sample_udp();
        let output = generate_etherparse(&proto);

        assert!(output.contains("impl UDPHeader"));
        assert!(output.contains("from_slice"));
    }

    #[test]
    fn test_etherparse_gen_mappings_load() {
        let m = type_mapping::load_etherparse_gen_mappings(None).unwrap();
        assert_eq!(m.rust_type(&FieldType::Uint, 16), Some("u16"));
        assert_eq!(m.rust_type(&FieldType::Ipv4Addr, 32), Some("[u8; 4]"));
        assert_eq!(m.rust_type(&FieldType::MacAddr, 48), Some("[u8; 6]"));
        assert_eq!(m.newtype("protocol"), Some("IpNumber"));
        assert_eq!(m.newtype("ether_type"), Some("EtherType"));
    }
}
