use crate::ir::{Endian, FieldType, ProtocolDef};

use super::canonical_to_snake;

/// Generate a Kaitai Struct .ksy YAML definition from a ProtocolDef.
pub fn generate_kaitai_ksy(proto: &ProtocolDef) -> String {
    let snake = canonical_to_snake(&proto.name);
    let endian = dominant_endian(proto);

    let mut out = String::new();

    // meta section
    out.push_str("meta:\n");
    out.push_str(&format!("  id: {}\n", snake));
    out.push_str(&format!("  title: {}\n", proto.name));
    out.push_str("  license: CC0-1.0\n");
    out.push_str("  ks-version: 0.8\n");
    out.push_str(&format!("  endian: {}\n", endian_str(&endian)));

    // doc section
    out.push_str(&format!(
        "doc: |\n  {} protocol header — {} bytes minimum.\n  Auto-generated by proto-audit from IR definition.\n",
        proto.name,
        proto.min_header_bits / 8
    ));

    // seq section
    out.push_str("seq:\n");

    // Fields before the first repeat group are the fixed prefix; the repeated
    // region (and its pre-expanded instances in `fields`) is emitted as typed,
    // repeated sub-structures below instead of flattened instances.
    let prefix_end = proto
        .repeats
        .iter()
        .map(|r| r.start_bits)
        .min()
        .unwrap_or(u32::MAX);

    for field in proto.fields.iter().filter(|f| f.offset_bits < prefix_end) {
        push_kaitai_field(&mut out, "  ", &field.name, field.size_bits,
                          &field.field_type, &field.endian, &endian,
                          &field.description);
    }

    for group in &proto.repeats {
        let gid = kaitai_id(&group.name);
        out.push_str(&format!("  - id: {}\n", gid));
        out.push_str(&format!("    type: {}_element\n", gid));
        match &group.terminator {
            crate::ir::RepeatTerm::Count { field } => {
                out.push_str("    repeat: expr\n");
                out.push_str(&format!("    repeat-expr: {}\n", kaitai_id(field)));
            }
            crate::ir::RepeatTerm::EndMark { .. } => {
                // Stop when a degenerate element appears (its first field, the
                // TLV type, is 0 — e.g. the MRP/MRPDU End Mark).
                let sentinel = group
                    .element
                    .first()
                    .map(|f| kaitai_id(&f.name))
                    .unwrap_or_else(|| "type".to_string());
                out.push_str("    repeat: until\n");
                out.push_str(&format!("    repeat-until: _.{} == 0\n", sentinel));
            }
            crate::ir::RepeatTerm::Length { .. } | crate::ir::RepeatTerm::ToEnd => {
                out.push_str("    repeat: eos\n");
            }
        }
    }

    // types: section — one sub-type per repeat group element.
    if !proto.repeats.is_empty() {
        out.push_str("types:\n");
        for group in &proto.repeats {
            out.push_str(&format!("  {}_element:\n", kaitai_id(&group.name)));
            out.push_str("    seq:\n");
            for field in &group.element {
                push_kaitai_field(&mut out, "      ", &field.name, field.size_bits,
                                  &field.field_type, &field.endian, &endian,
                                  &field.description);
            }
        }
    }

    out
}

/// Sanitise a name into a valid Kaitai identifier.
fn kaitai_id(name: &str) -> String {
    name.to_lowercase().replace(' ', "_").replace('-', "_").replace('.', "_")
}

/// Emit one `seq` field entry at the given item indent (attributes are indented
/// two spaces deeper).
#[allow(clippy::too_many_arguments)]
fn push_kaitai_field(
    out: &mut String,
    item_indent: &str,
    name: &str,
    size_bits: u32,
    field_type: &FieldType,
    field_endian: &Endian,
    dominant: &Endian,
    description: &str,
) {
    let attr_indent = format!("{}  ", item_indent);
    out.push_str(&format!("{}- id: {}\n", item_indent, kaitai_id(name)));
    match ir_to_kaitai_type(size_bits, field_type, field_endian, dominant) {
        KaitaiType::Primitive(t) => out.push_str(&format!("{}type: {}\n", attr_indent, t)),
        KaitaiType::FixedSize(sz) => out.push_str(&format!("{}size: {}\n", attr_indent, sz)),
        KaitaiType::Bits(b) => out.push_str(&format!("{}type: b{}\n", attr_indent, b)),
    }
    if !description.is_empty() {
        let escaped = description.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!("{}doc: \"{}\"\n", attr_indent, escaped));
    }
}

/// Generate a Kaitai .ksy as a new-file patch (--- /dev/null → +++ b/network/proto_audit/<name>.ksy).
pub fn generate_kaitai_patch(proto: &ProtocolDef) -> Option<String> {
    if proto.fields.is_empty() {
        return None;
    }
    let snake = canonical_to_snake(&proto.name);
    let body = generate_kaitai_ksy(proto);
    let num_lines = body.lines().count();

    let mut out = String::new();
    out.push_str("--- /dev/null\n");
    out.push_str(&format!("+++ b/network/proto_audit/{}.ksy\n", snake));
    out.push_str(&format!("@@ -0,0 +1,{} @@\n", num_lines));
    for line in body.lines() {
        out.push('+');
        out.push_str(line);
        out.push('\n');
    }
    Some(out)
}

enum KaitaiType {
    Primitive(String),
    FixedSize(u32),
    Bits(u32),
}

/// Map IR field to Kaitai type string.
fn ir_to_kaitai_type(bits: u32, ft: &FieldType, field_endian: &Endian, default_endian: &Endian) -> KaitaiType {
    // Sub-byte fields use bit types
    if bits < 8 || bits % 8 != 0 {
        return KaitaiType::Bits(bits);
    }

    let bytes = bits / 8;

    // Address types use fixed size
    match ft {
        FieldType::MacAddr => return KaitaiType::FixedSize(6),
        FieldType::Ipv4Addr => return KaitaiType::Primitive("u4be".to_string()),
        FieldType::Ipv6Addr => return KaitaiType::FixedSize(16),
        _ => {}
    }

    // For >8-byte fields (e.g., char[8] stock symbols), use fixed size
    if bytes > 8 {
        return KaitaiType::FixedSize(bytes);
    }

    // Standard integer types — use endian suffix if different from meta default
    let endian_suffix = match field_endian {
        Endian::Big if *default_endian == Endian::Big => "",
        Endian::Little if *default_endian == Endian::Little => "",
        Endian::Big => "be",
        Endian::Little => "le",
        Endian::Na => "",
    };

    let base = match bytes {
        1 => "u1",
        2 => "u2",
        3 | 4 => "u4",
        5..=8 => "u8",
        _ => return KaitaiType::FixedSize(bytes),
    };

    if endian_suffix.is_empty() {
        KaitaiType::Primitive(base.to_string())
    } else {
        KaitaiType::Primitive(format!("{}{}", base, endian_suffix))
    }
}

/// Determine the dominant endianness in the protocol for the meta.endian field.
fn dominant_endian(proto: &ProtocolDef) -> Endian {
    let mut big = 0u32;
    let mut little = 0u32;
    for f in &proto.fields {
        if f.size_bits > 8 {
            match f.endian {
                Endian::Big => big += 1,
                Endian::Little => little += 1,
                _ => {}
            }
        }
    }
    if little > big { Endian::Little } else { Endian::Big }
}

fn endian_str(e: &Endian) -> &'static str {
    match e {
        Endian::Little => "le",
        _ => "be",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn sample_udp() -> ProtocolDef {
        ProtocolDef::new("UDP", 64).with_fields(vec![
            FieldDef::new("src_port", 0, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Source port"),
            FieldDef::new("dst_port", 16, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Destination port"),
            FieldDef::new("length", 32, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Datagram length"),
            FieldDef::new("checksum", 48, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Checksum"),
        ])
    }

    #[test]
    fn test_generate_kaitai_ksy_basic() {
        let proto = sample_udp();
        let output = generate_kaitai_ksy(&proto);

        assert!(output.contains("meta:"));
        assert!(output.contains("  id: udp"));
        assert!(output.contains("  title: UDP"));
        assert!(output.contains("  endian: be"));
        assert!(output.contains("seq:"));
        assert!(output.contains("  - id: src_port"));
        assert!(output.contains("    type: u2"));
        assert!(output.contains("  - id: checksum"));
    }

    #[test]
    fn test_generate_kaitai_patch_format() {
        let proto = sample_udp();
        let patch = generate_kaitai_patch(&proto).unwrap();

        assert!(patch.starts_with("--- /dev/null\n"));
        assert!(patch.contains("+++ b/network/proto_audit/udp.ksy"));
        assert!(patch.contains("+meta:"));
        assert!(patch.contains("+seq:"));
    }

    #[test]
    fn test_generate_kaitai_empty_fields() {
        let proto = ProtocolDef::new("Empty", 0);
        assert!(generate_kaitai_patch(&proto).is_none());
    }

    #[test]
    fn test_kaitai_little_endian() {
        let proto = ProtocolDef::new("SBE_Test", 32).with_fields(vec![
            FieldDef::new("block_length", 0, 16, FieldType::Uint)
                .with_endian(Endian::Little),
            FieldDef::new("template_id", 16, 16, FieldType::Uint)
                .with_endian(Endian::Little),
        ]);
        let output = generate_kaitai_ksy(&proto);
        assert!(output.contains("  endian: le"));
        assert!(output.contains("    type: u2"));
    }

    #[test]
    fn test_kaitai_sub_byte_fields() {
        let proto = ProtocolDef::new("Bitfield", 16).with_fields(vec![
            FieldDef::new("version", 0, 4, FieldType::Uint),
            FieldDef::new("ihl", 4, 4, FieldType::Uint),
            FieldDef::new("tos", 8, 8, FieldType::Uint),
        ]);
        let output = generate_kaitai_ksy(&proto);
        assert!(output.contains("    type: b4"));
        assert!(output.contains("    type: u1"));
    }
}
