use crate::ir::{Endian, FieldType, ProtocolDef};

/// Generate an OMI-style packed C typedef struct from a ProtocolDef.
///
/// Output matches the format parsed by `extractors::omi::parse_omi_struct()`:
/// ```c
/// #pragma pack(push, 1)
/// typedef struct {
///     uint16_t FieldName;
///     char Stock[8];
/// } ProtoNameT;
/// #pragma pack(pop)
/// ```
pub fn generate_omi_struct(proto: &ProtocolDef) -> String {
    let struct_name = format!("{}T", proto.name.replace(' ', "").replace('-', ""));
    let mut out = String::new();

    out.push_str(&format!(
        "/* Auto-generated by proto-audit from IR definition.\n * Protocol: {}\n */\n\n",
        proto.name
    ));
    out.push_str("#pragma pack(push, 1)\n");
    out.push_str("typedef struct {\n");

    for field in &proto.fields {
        let c_type = ir_to_omi_type(&field.field_type, field.size_bits, &field.endian);
        let field_name = omi_field_name(&field.name);

        if let Some((base, count)) = c_type.strip_suffix(']').and_then(|s| {
            let idx = s.find('[')?;
            Some((s[..idx].to_string(), s[idx + 1..].to_string()))
        }) {
            out.push_str(&format!("    {} {}[{}];\n", base, field_name, count));
        } else {
            out.push_str(&format!("    {} {};\n", c_type, field_name));
        }
    }

    out.push_str(&format!("}} {};\n", struct_name));
    out.push_str("#pragma pack(pop)\n");

    out
}

/// Generate an OMI struct as a new-file patch.
pub fn generate_omi_patch(proto: &ProtocolDef) -> Option<String> {
    if proto.fields.is_empty() {
        return None;
    }
    let snake = super::canonical_to_snake(&proto.name);
    let body = generate_omi_struct(proto);
    let num_lines = body.lines().count();

    let mut out = String::new();
    out.push_str("--- /dev/null\n");
    out.push_str(&format!("+++ b/omi/proto_audit/{}.h\n", snake));
    out.push_str(&format!("@@ -0,0 +1,{} @@\n", num_lines));
    for line in body.lines() {
        out.push('+');
        out.push_str(line);
        out.push('\n');
    }
    Some(out)
}

/// Map IR field type + size to OMI C type.
fn ir_to_omi_type(ft: &FieldType, bits: u32, endian: &Endian) -> String {
    // Char/Na endian fields: use char or char[N]
    if *endian == Endian::Na || matches!(ft, FieldType::Bytes) {
        if bits == 8 {
            return "char".to_string();
        }
        if bits > 8 && bits % 8 == 0 {
            return format!("char[{}]", bits / 8);
        }
    }

    match bits {
        8 => "uint8_t".to_string(),
        16 => "uint16_t".to_string(),
        32 => match ft {
            FieldType::Ipv4Addr => "uint32_t".to_string(),
            _ => "uint32_t".to_string(),
        },
        64 => "uint64_t".to_string(),
        _ if bits % 8 == 0 => format!("char[{}]", bits / 8),
        _ => "uint8_t".to_string(),
    }
}

/// Convert field name to OMI convention (PascalCase, no underscores).
fn omi_field_name(name: &str) -> String {
    // If already PascalCase, return as-is
    if !name.contains('_') && !name.contains('.') && !name.contains('-') {
        return name.to_string();
    }
    // Convert snake_case to PascalCase
    name.split(|c: char| c == '_' || c == '.' || c == '-')
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut chars = s.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    upper + &chars.as_str().to_string()
                }
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn sample_itch_addorder() -> ProtocolDef {
        ProtocolDef::new("ITCH v5 AddOrder", 264).with_fields(vec![
            FieldDef::new("StockLocate", 0, 16, FieldType::Uint).with_endian(Endian::Big),
            FieldDef::new("TrackingNumber", 16, 16, FieldType::Uint).with_endian(Endian::Big),
            FieldDef::new("Timestamp", 32, 8, FieldType::Uint).with_endian(Endian::Na),
            FieldDef::new("OrderReferenceNumber", 40, 64, FieldType::Uint).with_endian(Endian::Big),
            FieldDef::new("BuySellIndicator", 104, 8, FieldType::Enum).with_endian(Endian::Na),
            FieldDef::new("Shares", 112, 32, FieldType::Uint).with_endian(Endian::Big),
            FieldDef::new("Stock", 144, 64, FieldType::Bytes).with_endian(Endian::Na),
            FieldDef::new("Price", 208, 32, FieldType::Uint).with_endian(Endian::Big),
        ])
    }

    #[test]
    fn test_generate_omi_struct() {
        let proto = sample_itch_addorder();
        let output = generate_omi_struct(&proto);
        assert!(output.contains("#pragma pack(push, 1)"));
        assert!(output.contains("typedef struct {"));
        assert!(output.contains("uint16_t StockLocate;"));
        assert!(output.contains("char Timestamp;"));
        assert!(output.contains("uint64_t OrderReferenceNumber;"));
        assert!(output.contains("char BuySellIndicator;"));
        assert!(output.contains("char Stock[8];"));
        assert!(output.contains("} ITCHv5AddOrderT;"));
        assert!(output.contains("#pragma pack(pop)"));
    }

    #[test]
    fn test_generate_omi_patch() {
        let proto = sample_itch_addorder();
        let patch = generate_omi_patch(&proto).unwrap();
        assert!(patch.starts_with("--- /dev/null"));
        assert!(patch.contains("+++ b/omi/proto_audit/itch_v5_addorder.h"));
    }

    #[test]
    fn test_empty_fields_returns_none() {
        let proto = ProtocolDef::new("Empty", 0);
        assert!(generate_omi_patch(&proto).is_none());
    }
}
