use crate::ir::{Endian, FieldType, ProtocolDef};
use crate::type_mapping;

use super::{canonical_to_pascal, canonical_to_snake, format_value};

/// Generate a Python Scapy Packet class definition from a ProtocolDef.
pub fn generate_scapy(proto: &ProtocolDef) -> String {
    let mappings = type_mapping::load_scapy_gen_mappings(None)
        .expect("embedded scapy_gen mappings should always parse");

    let class_name = canonical_to_pascal(&proto.name);

    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "# Auto-generated by proto-audit from IR definition.\n\
         # Protocol: {}\n\n",
        proto.name
    ));

    // Imports
    out.push_str("from scapy.packet import Packet, bind_layers\n");
    out.push_str("from scapy.fields import *\n\n\n");

    // Class definition
    out.push_str(&format!("class {}(Packet):\n", class_name));
    out.push_str(&format!("    name = \"{}\"\n", proto.name));
    out.push_str("    fields_desc = [\n");

    for field in &proto.fields {
        let scapy_name = field
            .source_names
            .get("scapy")
            .map(|s| s.as_str())
            .unwrap_or(&field.name);

        let field_class = determine_scapy_class(&field.field_type, field.size_bits,
                                                 scapy_name, &field.endian,
                                                 &field.flag_names, &mappings);

        let field_str = format_scapy_field(&field_class, scapy_name, field.size_bits,
                                           &field.field_type, &field.default_value,
                                           &field.flag_names);

        out.push_str(&format!("        {},\n", field_str));
    }

    out.push_str("    ]\n");

    // bind_layers from dispatch table
    if !proto.dispatch_table.is_empty() {
        out.push_str("\n\n");
        for entry in &proto.dispatch_table {
            if let Some(ref dispatch_field) = proto.dispatch_field {
                let dispatch_name = proto
                    .fields
                    .iter()
                    .find(|f| &f.name == dispatch_field)
                    .and_then(|f| f.source_names.get("scapy"))
                    .map(|s| s.as_str())
                    .unwrap_or(dispatch_field.as_str());

                out.push_str(&format!(
                    "bind_layers({}, {}, {}={})\n",
                    class_name,
                    canonical_to_pascal(&entry.protocol),
                    dispatch_name,
                    format_value(entry.value)
                ));
            }
        }
    }

    out
}

/// Generate a Scapy module as a new-file patch (--- /dev/null → +++ b/scapy/proto_audit/<name>.py).
///
/// Output is a self-contained Python module with imports, class, and fields_desc.
/// Suitable for use with `gen-patches --target scapy`.
pub fn generate_scapy_patch(proto: &ProtocolDef) -> Option<String> {
    if proto.fields.is_empty() {
        return None;
    }
    let snake = canonical_to_snake(&proto.name);
    let body = generate_scapy(proto);
    let num_lines = body.lines().count();

    let mut out = String::new();
    out.push_str("--- /dev/null\n");
    out.push_str(&format!("+++ b/scapy/proto_audit/{}.py\n", snake));
    out.push_str(&format!("@@ -0,0 +1,{} @@\n", num_lines));
    for line in body.lines() {
        out.push('+');
        out.push_str(line);
        out.push('\n');
    }
    Some(out)
}

/// Determine the Scapy field class for a given IR field.
fn determine_scapy_class(
    ft: &FieldType,
    bits: u32,
    name: &str,
    endian: &Endian,
    flag_names: &Option<Vec<String>>,
    mappings: &type_mapping::ScapyGenMappings,
) -> String {
    // 1. Name overrides (e.g., src → SourceIPField)
    if let Some(cls) = mappings.name_override(name) {
        return cls.to_string();
    }

    // 2. FlagsField with flag_names
    if *ft == FieldType::Flags && flag_names.is_some() {
        return "FlagsField".to_string();
    }

    // 3. Generic (type, size) mapping
    let base_class = mappings
        .field_class(ft, bits)
        .unwrap_or_else(|| {
            if bits <= 8 { "ByteField" }
            else if bits <= 16 { "ShortField" }
            else if bits <= 32 { "IntField" }
            else { "LongField" }
        })
        .to_string();

    // 4. Apply LE prefix if little-endian (skip for 1-byte fields — no endianness)
    if *endian == Endian::Little && bits > 8 {
        if let Some(le) = mappings.le_variant(&base_class) {
            return le.to_string();
        }
    }

    base_class
}

/// Format a Scapy field constructor string.
fn format_scapy_field(
    class: &str,
    name: &str,
    bits: u32,
    ft: &FieldType,
    default: &Option<String>,
    flag_names: &Option<Vec<String>>,
) -> String {
    match class {
        "BitField" => {
            format!(
                "BitField(\"{}\", {}, {})",
                name,
                default.as_deref().unwrap_or("0"),
                bits
            )
        }
        c if c.ends_with("EnumField") => {
            // EnumField types need an enum dict as 3rd arg; use empty dict
            // if no dispatch values are available (common for OMI fields).
            format!(
                "{}(\"{}\", {}, {{}})",
                c,
                name,
                default.as_deref().unwrap_or("0")
            )
        }
        "FlagsField" => {
            if let Some(ref names) = flag_names {
                let names_str: Vec<String> = names.iter().map(|n| format!("\"{}\"", n)).collect();
                format!(
                    "FlagsField(\"{}\", {}, {}, [{}])",
                    name,
                    default.as_deref().unwrap_or("0"),
                    bits,
                    names_str.join(", ")
                )
            } else {
                format!(
                    "FlagsField(\"{}\", {}, {})",
                    name,
                    default.as_deref().unwrap_or("0"),
                    bits
                )
            }
        }
        _ => {
            if let Some(ref d) = default {
                format!("{}(\"{}\", {})", class, name, d)
            } else {
                let default_val = match ft {
                    FieldType::Ipv4Addr => "\"0.0.0.0\"",
                    FieldType::Ipv6Addr => "\"::\"",
                    FieldType::MacAddr => "\"00:00:00:00:00:00\"",
                    _ => "0",
                };
                format!("{}(\"{}\", {})", class, name, default_val)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn sample_udp() -> ProtocolDef {
        ProtocolDef::new("UDP", 64).with_fields(vec![
            FieldDef::new("src_port", 0, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Source port")
                .with_source_name("scapy", "sport").with_default_value("53"),
            FieldDef::new("dst_port", 16, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Destination port")
                .with_source_name("scapy", "dport").with_default_value("53"),
            FieldDef::new("length", 32, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Datagram length")
                .with_length(None).with_source_name("scapy", "len"),
            FieldDef::new("checksum", 48, 16, FieldType::Uint)
                .with_endian(Endian::Big).with_description("Checksum")
                .with_source_name("scapy", "chksum"),
        ])
    }

    fn sample_ipv4_rich() -> ProtocolDef {
        ProtocolDef::new("IPv4", 160)
            .with_variable_length()
            .with_dispatch_field("protocol")
            .with_dispatch_table(vec![
                DispatchEntry { value: 6, protocol: "TCP".into(), sources: vec!["scapy".into()] },
                DispatchEntry { value: 17, protocol: "UDP".into(), sources: vec!["scapy".into()] },
            ])
            .with_fields(vec![
                FieldDef::new("version", 0, 4, FieldType::Uint)
                    .with_description("IP version")
                    .with_source_name("scapy", "version").with_default_value("4"),
                FieldDef::new("ihl", 4, 4, FieldType::Uint)
                    .with_description("Header length")
                    .with_length(Some(4)).with_source_name("scapy", "ihl"),
                FieldDef::new("tos", 8, 8, FieldType::Uint)
                    .with_source_name("scapy", "tos").with_default_value("0"),
                FieldDef::new("total_length", 16, 16, FieldType::Uint)
                    .with_endian(Endian::Big).with_source_name("scapy", "len"),
                FieldDef::new("flags", 48, 3, FieldType::Flags)
                    .with_description("IP flags")
                    .with_source_name("scapy", "flags")
                    .with_flag_names(vec!["Reserved".into(), "DF".into(), "MF".into()]),
                FieldDef::new("protocol", 72, 8, FieldType::Enum)
                    .with_description("Next protocol").with_dispatch()
                    .with_source_name("scapy", "proto").with_default_value("0"),
                FieldDef::new("src_addr", 96, 32, FieldType::Ipv4Addr)
                    .with_endian(Endian::Big).with_description("Source address")
                    .with_source_name("scapy", "src"),
                FieldDef::new("dst_addr", 128, 32, FieldType::Ipv4Addr)
                    .with_endian(Endian::Big).with_description("Destination address")
                    .with_source_name("scapy", "dst"),
            ])
    }

    #[test]
    fn test_generate_scapy_udp() {
        let proto = sample_udp();
        let output = generate_scapy(&proto);

        assert!(output.contains("class UDP(Packet)"));
        assert!(output.contains("name = \"UDP\""));
        assert!(output.contains("fields_desc = ["));
        assert!(output.contains("\"sport\", 53"));
        assert!(output.contains("XShortField(\"chksum\""));
    }

    #[test]
    fn test_generate_scapy_ipv4() {
        let proto = sample_ipv4_rich();
        let output = generate_scapy(&proto);

        assert!(output.contains("class IPv4(Packet)"));
        assert!(output.contains("BitField(\"version\", 4, 4)"));
        assert!(output.contains("FlagsField(\"flags\""));
        assert!(output.contains("\"Reserved\""));
        assert!(output.contains("\"DF\""));
        assert!(output.contains("\"MF\""));
        assert!(output.contains("SourceIPField(\"src\""));
        assert!(output.contains("DestIPField(\"dst\""));
        assert!(output.contains("ByteEnumField(\"proto\""));
    }

    #[test]
    fn test_generate_scapy_bind_layers() {
        let proto = sample_ipv4_rich();
        let output = generate_scapy(&proto);

        assert!(output.contains("bind_layers(IPv4, TCP, proto=6)"));
        assert!(output.contains("bind_layers(IPv4, UDP, proto=17)"));
    }

    #[test]
    fn test_generate_scapy_imports() {
        let proto = sample_udp();
        let output = generate_scapy(&proto);

        assert!(output.contains("from scapy.packet import Packet, bind_layers"));
        assert!(output.contains("from scapy.fields import *"));
    }

    #[test]
    fn test_scapy_gen_mappings_load() {
        let m = type_mapping::load_scapy_gen_mappings(None).unwrap();
        assert_eq!(m.field_class(&FieldType::Uint, 8), Some("ByteField"));
        assert_eq!(m.field_class(&FieldType::Uint, 16), Some("ShortField"));
        assert_eq!(m.field_class(&FieldType::Ipv4Addr, 32), Some("IPField"));
        assert_eq!(m.field_class(&FieldType::Flags, 3), Some("FlagsField"));
        assert_eq!(m.name_override("src"), Some("SourceIPField"));
        assert_eq!(m.le_variant("ShortField"), Some("LEShortField"));
    }
}
