use crate::ir::{Endian, FieldType, ProtocolDef};

/// Generate a Suricata-style Rust struct with a nom parser from a ProtocolDef.
///
/// Output matches the format parsed by `extractors::suricata`:
/// ```rust
/// /// Protocol description
/// pub struct ProtoHeader {
///     pub field_name: u32,
/// }
///
/// pub fn parse_proto(i: &[u8]) -> IResult<&[u8], ProtoHeader> {
///     let (i, field_name) = be_u32(i)?;
///     ...
/// }
/// ```
pub fn generate_suricata_struct(proto: &ProtocolDef) -> String {
    let struct_name = suricata_struct_name(&proto.name);
    let parse_fn_name = suricata_parse_fn_name(&proto.name);

    let mut out = String::new();

    out.push_str(&format!(
        "// Auto-generated by proto-audit from IR definition.\n\
         // Protocol: {}\n\n\
         use nom::number::streaming::*;\n\
         use nom::IResult;\n\n",
        proto.name
    ));

    // Struct definition
    out.push_str(&format!("/// {} protocol header\n", proto.name));
    out.push_str(&format!("pub struct {} {{\n", struct_name));

    for field in &proto.fields {
        let rust_type = ir_to_suricata_type(&field.field_type, field.size_bits);
        let field_name = suricata_field_name(&field.name);
        if !field.description.is_empty() {
            out.push_str(&format!("    /// {}\n", field.description));
        }
        out.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
    }

    out.push_str("}\n\n");

    // Parser function (needed for endianness detection by the suricata extractor)
    out.push_str(&format!(
        "pub fn {}(i: &[u8]) -> IResult<&[u8], {}> {{\n",
        parse_fn_name, struct_name
    ));

    for field in &proto.fields {
        let field_name = suricata_field_name(&field.name);
        let nom_fn = nom_parser_for_field(&field.field_type, field.size_bits, &field.endian);
        out.push_str(&format!("    let (i, {}) = {}(i)?;\n", field_name, nom_fn));
    }

    out.push_str(&format!("    Ok((i, {} {{\n", struct_name));
    for field in &proto.fields {
        let field_name = suricata_field_name(&field.name);
        out.push_str(&format!("        {},\n", field_name));
    }
    out.push_str("    }))\n}\n");

    out
}

/// Generate a Suricata struct as a new-file patch.
pub fn generate_suricata_patch(proto: &ProtocolDef) -> Option<String> {
    if proto.fields.is_empty() {
        return None;
    }
    let snake = super::canonical_to_snake(&proto.name);
    let body = generate_suricata_struct(proto);
    let num_lines = body.lines().count();

    let mut out = String::new();
    out.push_str("--- /dev/null\n");
    out.push_str(&format!("+++ b/suricata/proto_audit/{}.rs\n", snake));
    out.push_str(&format!("@@ -0,0 +1,{} @@\n", num_lines));
    for line in body.lines() {
        out.push('+');
        out.push_str(line);
        out.push('\n');
    }
    Some(out)
}

/// Map IR field type + size to Rust type.
fn ir_to_suricata_type(ft: &FieldType, bits: u32) -> String {
    match ft {
        FieldType::Ipv4Addr if bits == 32 => "[u8; 4]".to_string(),
        FieldType::Ipv6Addr if bits == 128 => "[u8; 16]".to_string(),
        FieldType::MacAddr if bits == 48 => "[u8; 6]".to_string(),
        _ => match bits {
            8 => "u8".to_string(),
            16 => "u16".to_string(),
            32 => "u32".to_string(),
            64 => "u64".to_string(),
            _ if bits > 64 && bits % 8 == 0 => format!("[u8; {}]", bits / 8),
            _ => "u8".to_string(),
        },
    }
}

/// Get the nom parser function for a field (used in the parse function).
fn nom_parser_for_field(ft: &FieldType, bits: u32, endian: &Endian) -> String {
    let prefix = match endian {
        Endian::Little => "le",
        _ => "be",
    };

    match ft {
        FieldType::Ipv4Addr if bits == 32 => "take4".to_string(),
        FieldType::Ipv6Addr if bits == 128 => "take16".to_string(),
        FieldType::MacAddr if bits == 48 => "take6".to_string(),
        _ => match bits {
            8 => format!("{}_u8", prefix),
            16 => format!("{}_u16", prefix),
            32 => format!("{}_u32", prefix),
            64 => format!("{}_u64", prefix),
            _ => format!("{}_u8", prefix),
        },
    }
}

/// Convert protocol name to Suricata struct name (PascalCase + "Header").
fn suricata_struct_name(name: &str) -> String {
    let pascal = name
        .replace('_', "")
        .replace('.', "")
        .replace('-', "")
        .replace(' ', "");
    format!("{}Header", pascal)
}

/// Convert protocol name to parse function name.
fn suricata_parse_fn_name(name: &str) -> String {
    let snake = super::canonical_to_snake(name);
    format!("parse_{}", snake)
}

/// Convert field name to Suricata convention (snake_case).
fn suricata_field_name(name: &str) -> String {
    let name = name.to_lowercase()
        .replace('.', "_")
        .replace('-', "_")
        .replace(' ', "_");
    // Avoid Rust keywords
    match name.as_str() {
        "type" => "r#type".to_string(),
        "mod" => "r#mod".to_string(),
        "ref" => "r#ref".to_string(),
        _ => name,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn sample_dns_header() -> ProtocolDef {
        ProtocolDef::new("DNS", 96)
            .with_fields(vec![
                FieldDef::new("id", 0, 16, FieldType::Uint)
                    .with_endian(Endian::Big)
                    .with_description("Transaction ID"),
                FieldDef::new("flags", 16, 16, FieldType::Uint)
                    .with_endian(Endian::Big)
                    .with_description("Flags"),
                FieldDef::new("qdcount", 32, 16, FieldType::Uint)
                    .with_endian(Endian::Big),
                FieldDef::new("ancount", 48, 16, FieldType::Uint)
                    .with_endian(Endian::Big),
                FieldDef::new("nscount", 64, 16, FieldType::Uint)
                    .with_endian(Endian::Big),
                FieldDef::new("arcount", 80, 16, FieldType::Uint)
                    .with_endian(Endian::Big),
            ])
    }

    #[test]
    fn test_generate_suricata_struct() {
        let proto = sample_dns_header();
        let output = generate_suricata_struct(&proto);
        assert!(output.contains("pub struct DNSHeader {"));
        assert!(output.contains("pub id: u16,"));
        assert!(output.contains("pub flags: u16,"));
        assert!(output.contains("pub fn parse_dns("));
        assert!(output.contains("let (i, id) = be_u16(i)?;"));
    }

    #[test]
    fn test_generate_suricata_patch() {
        let proto = sample_dns_header();
        let patch = generate_suricata_patch(&proto).unwrap();
        assert!(patch.starts_with("--- /dev/null"));
        assert!(patch.contains("+++ b/suricata/proto_audit/dns.rs"));
    }

    #[test]
    fn test_empty_fields_returns_none() {
        let proto = ProtocolDef::new("Empty", 0);
        assert!(generate_suricata_patch(&proto).is_none());
    }

    #[test]
    fn test_little_endian_parser() {
        let proto = ProtocolDef::new("SBE", 64).with_fields(vec![
            FieldDef::new("block_length", 0, 16, FieldType::Uint).with_endian(Endian::Little),
            FieldDef::new("template_id", 16, 16, FieldType::Uint).with_endian(Endian::Little),
        ]);
        let output = generate_suricata_struct(&proto);
        assert!(output.contains("let (i, block_length) = le_u16(i)?;"));
        assert!(output.contains("let (i, template_id) = le_u16(i)?;"));
    }
}
