//! Wireshark Lua post-dissector generator.
//!
//! Generates Lua scripts that decompose opaque netlink inet_diag attribute
//! payloads (tcp_info, bbr_info, meminfo, skmeminfo, etc.) into individually
//! named ProtoFields. When loaded via `tshark -X lua_script:<path>`, each
//! attribute appears as a fully dissected subtree in PDML output.
//!
//! The generated Lua registers as a post-dissector on packets containing
//! the `netlink-sock_diag` protocol, walks the RTAttr TLV chain after the
//! 72-byte inet_diag_msg body, and dispatches to per-attribute dissectors.

use crate::ir::{Endian, FieldType, ProtocolDef};

use super::canonical_to_snake;

// ---------------------------------------------------------------------------
// Attribute type ID → dissector name mapping
// ---------------------------------------------------------------------------

/// Known inet_diag attribute types with their proto-audit canonical names.
const INET_DIAG_ATTRS: &[(u16, &str)] = &[
    (1, "NL_Diag_MemInfo"),
    (2, "NL_Diag_TCPInfo"),
    (3, "NL_Diag_VegasInfo"),
    (7, "NL_Diag_SkMemInfo"),
    (9, "NL_Diag_DCTCPInfo"),
    (16, "NL_Diag_BBRInfo"),
];

// ---------------------------------------------------------------------------
// IR → Lua type mapping
// ---------------------------------------------------------------------------

/// Map an IR FieldType + size to a Lua ProtoField constructor and base.
fn lua_proto_field(ft: &FieldType, size_bits: u32) -> (&'static str, &'static str) {
    match ft {
        FieldType::Ipv4Addr => ("ProtoField.ipv4", ""),
        FieldType::Ipv6Addr => ("ProtoField.ipv6", ""),
        FieldType::MacAddr => ("ProtoField.ether", ""),
        FieldType::Bytes | FieldType::Pad => ("ProtoField.bytes", ""),
        FieldType::Flags => match size_bits {
            0..=8 => ("ProtoField.uint8", ", base.HEX"),
            9..=16 => ("ProtoField.uint16", ", base.HEX"),
            17..=32 => ("ProtoField.uint32", ", base.HEX"),
            _ => ("ProtoField.uint64", ", base.HEX"),
        },
        FieldType::Sint => match size_bits {
            0..=8 => ("ProtoField.int8", ", base.DEC"),
            9..=16 => ("ProtoField.int16", ", base.DEC"),
            17..=32 => ("ProtoField.int32", ", base.DEC"),
            _ => ("ProtoField.int64", ", base.DEC"),
        },
        _ => match size_bits {
            // Uint, Enum, and default
            0..=8 => ("ProtoField.uint8", ", base.DEC"),
            9..=16 => ("ProtoField.uint16", ", base.DEC"),
            17..=32 => ("ProtoField.uint32", ", base.DEC"),
            _ => ("ProtoField.uint64", ", base.DEC"),
        },
    }
}

/// Return the Lua `add` or `add_le` method based on endianness.
fn lua_add_method(endian: &Endian, size_bits: u32) -> &'static str {
    if size_bits <= 8 {
        return "add"; // single-byte: endianness doesn't apply
    }
    match endian {
        Endian::Big => "add",
        _ => "add_le", // Little and Na default to little-endian for netlink
    }
}

// ---------------------------------------------------------------------------
// Single-protocol generator
// ---------------------------------------------------------------------------

/// Generate a Wireshark Lua dissector for a single protocol definition.
///
/// Produces a self-contained Lua script with Proto, ProtoFields, dissector
/// function, and post-dissector registration.
pub fn generate_wireshark_lua_single(proto: &ProtocolDef) -> String {
    let snake = canonical_to_snake(&proto.name);
    let dissector_name = format!("inet_diag_{}", snake);

    let mut out = String::new();
    out.push_str(&format!(
        "-- Auto-generated by proto-audit from IR definition.\n\
         -- Protocol: {}\n\
         --\n\
         -- Load with: tshark -X lua_script:<this_file> -r capture.pcap -T pdml\n\n",
        proto.name
    ));

    generate_proto_block(&mut out, proto, &dissector_name, &snake);

    out.push('\n');
    out.push_str(&format!(
        "register_postdissector(proto_{})\n",
        snake
    ));

    out
}

/// Generate an aggregate Lua script for multiple inet_diag attribute protocols.
///
/// `protos` is a slice of `(attr_type_id, canonical_name, proto_def)` tuples.
/// The generated script walks the RTAttr chain and dispatches each attribute
/// to the matching per-type dissector.
pub fn generate_wireshark_lua(protos: &[(u16, &str, &ProtocolDef)]) -> String {
    let mut out = String::new();

    out.push_str(
        "-- Auto-generated by proto-audit from IR definitions.\n\
         -- Netlink INET_DIAG attribute dissectors.\n\
         --\n\
         -- Decomposes opaque inet_diag attribute payloads (tcp_info, bbr_info,\n\
         -- meminfo, skmeminfo, vegasinfo, dctcpinfo) into individual named fields.\n\
         --\n\
         -- Load with: tshark -X lua_script:<this_file> -r capture.pcap -T pdml\n\n",
    );

    // Generate Proto + ProtoField declarations for each attribute
    for (_, name, proto) in protos {
        let snake = canonical_to_snake(name);
        let dissector_name = format!("inet_diag_{}", snake);
        generate_proto_block(&mut out, proto, &dissector_name, &snake);
        out.push('\n');
    }

    // Generate the aggregate post-dissector that walks RTAttr chain
    out.push_str(
        "-- ================================================================\n\
         -- Aggregate post-dissector: walks RTAttr chain in netlink-sock_diag\n\
         -- ================================================================\n\n",
    );

    out.push_str("local proto_inet_diag_attrs = Proto(\"inet_diag_attrs\", \"INET_DIAG Attribute Dissectors\")\n\n");

    // Field to detect netlink-sock_diag packets
    out.push_str("local f_netlink_family = Field.new(\"netlink.family\")\n");
    out.push_str("local NETLINK_SOCK_DIAG = 4\n");
    out.push_str("local COOKED_HDR = 16\n");
    out.push_str("local NLMSGHDR = 16\n");
    out.push_str("local INET_DIAG_MSG = 72\n\n");

    out.push_str("function proto_inet_diag_attrs.dissector(buffer, pinfo, tree)\n");
    out.push_str("    local family = f_netlink_family()\n");
    out.push_str("    if not family then return end\n");
    out.push_str("    if family.value ~= NETLINK_SOCK_DIAG then return end\n\n");
    out.push_str("    -- Walk netlink messages in the packet\n");
    out.push_str("    local pkt_offset = COOKED_HDR\n");
    out.push_str("    while pkt_offset + NLMSGHDR <= buffer:len() do\n");
    out.push_str("        local nlmsg_len = buffer(pkt_offset, 4):le_uint()\n");
    out.push_str("        local nlmsg_type = buffer(pkt_offset + 4, 2):le_uint()\n");
    out.push_str("        if nlmsg_len < NLMSGHDR or pkt_offset + nlmsg_len > buffer:len() then break end\n");
    out.push_str("        if nlmsg_type == 3 then break end  -- NLMSG_DONE\n\n");
    out.push_str("        if nlmsg_type == 20 then  -- SOCK_DIAG_BY_FAMILY\n");
    out.push_str("            local attr_offset = pkt_offset + NLMSGHDR + INET_DIAG_MSG\n");
    out.push_str("            local msg_end = pkt_offset + nlmsg_len\n\n");
    out.push_str("            while attr_offset + 4 <= msg_end do\n");
    out.push_str("                local rta_len = buffer(attr_offset, 2):le_uint()\n");
    out.push_str("                local rta_type = buffer(attr_offset + 2, 2):le_uint()\n");
    out.push_str("                if rta_len < 4 then break end\n");
    out.push_str("                local payload_len = rta_len - 4\n");
    out.push_str("                local payload_off = attr_offset + 4\n\n");

    // Dispatch to per-attribute dissectors
    let mut first = true;
    for (attr_type, name, proto) in protos {
        let snake = canonical_to_snake(name);
        let keyword = if first { "if" } else { "elseif" };
        first = false;

        out.push_str(&format!(
            "                {} rta_type == {} then  -- {}\n",
            keyword, attr_type, name
        ));
        out.push_str(&format!(
            "                    local subtree = tree:add(proto_{}, buffer(payload_off, payload_len))\n",
            snake
        ));

        // Add each field
        for field in &proto.fields {
            if field.field_type == FieldType::Pad {
                continue;
            }
            let offset_bytes = field.offset_bits / 8;
            let size_bytes = field.size_bits / 8;
            if size_bytes == 0 {
                continue;
            }
            let add_method = lua_add_method(&field.endian, field.size_bits);
            let var_name = format!("f_{}_{}", snake, canonical_to_snake(&field.name));

            if proto.is_variable_length {
                out.push_str(&format!(
                    "                    if payload_len >= {} then subtree:{}({}, buffer(payload_off + {}, {})) end\n",
                    offset_bytes + size_bytes,
                    add_method,
                    var_name,
                    offset_bytes,
                    size_bytes
                ));
            } else {
                out.push_str(&format!(
                    "                    subtree:{}({}, buffer(payload_off + {}, {}))\n",
                    add_method, var_name, offset_bytes, size_bytes
                ));
            }
        }
    }

    if !protos.is_empty() {
        out.push_str("                end\n");
    }

    out.push_str("\n                -- Advance to next 4-byte aligned attribute\n");
    out.push_str("                attr_offset = attr_offset + math.ceil(rta_len / 4) * 4\n");
    out.push_str("            end\n");
    out.push_str("        end\n\n");
    out.push_str("        -- Advance to next netlink message (4-byte aligned)\n");
    out.push_str("        pkt_offset = pkt_offset + math.ceil(nlmsg_len / 4) * 4\n");
    out.push_str("    end\n");
    out.push_str("end\n\n");
    out.push_str("register_postdissector(proto_inet_diag_attrs)\n");

    out
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Generate the Proto + ProtoField declarations block for one protocol.
fn generate_proto_block(
    out: &mut String,
    proto: &ProtocolDef,
    dissector_name: &str,
    snake: &str,
) {
    // Proto declaration
    out.push_str(&format!(
        "local proto_{} = Proto(\"{}\", \"{}\")\n\n",
        snake, dissector_name, proto.name
    ));

    // ProtoField declarations
    let mut field_vars = Vec::new();
    for field in &proto.fields {
        if field.field_type == FieldType::Pad {
            continue;
        }
        let field_snake = canonical_to_snake(&field.name);
        let var_name = format!("f_{}_{}", snake, field_snake);
        let filter_name = format!("{}.{}", dissector_name, field_snake);
        let (proto_field, base) = lua_proto_field(&field.field_type, field.size_bits);

        let description = if field.description.is_empty() {
            field.name.clone()
        } else {
            field.description.clone()
        };

        if base.is_empty() {
            out.push_str(&format!(
                "local {} = {}(\"{}\", \"{}\")\n",
                var_name, proto_field, filter_name, description
            ));
        } else {
            out.push_str(&format!(
                "local {} = {}(\"{}\", \"{}\"{})\n",
                var_name, proto_field, filter_name, description, base
            ));
        }
        field_vars.push(var_name);
    }

    // fields table
    if !field_vars.is_empty() {
        out.push_str(&format!(
            "proto_{}.fields = {{ {} }}\n",
            snake,
            field_vars.join(", ")
        ));
    }

    out.push('\n');

    // Single-protocol dissector function (for generate_wireshark_lua_single)
    out.push_str(&format!(
        "function proto_{}.dissector(buffer, pinfo, tree)\n",
        snake
    ));
    out.push_str("    local offset = 0\n");
    out.push_str("    local subtree = tree:add(proto_");
    out.push_str(snake);
    out.push_str(", buffer())\n");

    for field in &proto.fields {
        if field.field_type == FieldType::Pad {
            continue;
        }
        let offset_bytes = field.offset_bits / 8;
        let size_bytes = field.size_bits / 8;
        if size_bytes == 0 {
            continue;
        }
        let field_snake = canonical_to_snake(&field.name);
        let var_name = format!("f_{}_{}", snake, field_snake);
        let add_method = lua_add_method(&field.endian, field.size_bits);

        if proto.is_variable_length {
            out.push_str(&format!(
                "    if buffer:len() >= {} then subtree:{}({}, buffer({}, {})) end\n",
                offset_bytes + size_bytes,
                add_method,
                var_name,
                offset_bytes,
                size_bytes
            ));
        } else {
            out.push_str(&format!(
                "    subtree:{}({}, buffer({}, {}))\n",
                add_method, var_name, offset_bytes, size_bytes
            ));
        }
    }

    out.push_str("end\n");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Endian, FieldDef, FieldType, ProtocolDef};

    fn sample_bbrinfo() -> ProtocolDef {
        ProtocolDef::new("NL_Diag_BBRInfo", 160).with_fields(vec![
            FieldDef::new("bbr_bw_lo", 0, 32, FieldType::Uint)
                .with_endian(Endian::Little)
                .with_description("Bandwidth low 32 bits"),
            FieldDef::new("bbr_bw_hi", 32, 32, FieldType::Uint)
                .with_endian(Endian::Little)
                .with_description("Bandwidth high 32 bits"),
            FieldDef::new("bbr_min_rtt", 64, 32, FieldType::Uint)
                .with_endian(Endian::Little)
                .with_description("Minimum RTT (us)"),
            FieldDef::new("bbr_pacing_gain", 96, 32, FieldType::Uint)
                .with_endian(Endian::Little)
                .with_description("Pacing gain"),
            FieldDef::new("bbr_cwnd_gain", 128, 32, FieldType::Uint)
                .with_endian(Endian::Little)
                .with_description("Cwnd gain"),
        ])
    }

    fn sample_tcpinfo_short() -> ProtocolDef {
        ProtocolDef::new("NL_Diag_TCPInfo", 1984)
            .with_variable_length()
            .with_fields(vec![
                FieldDef::new("state", 0, 8, FieldType::Uint)
                    .with_endian(Endian::Little)
                    .with_description("TCP state"),
                FieldDef::new("rto", 64, 32, FieldType::Uint)
                    .with_endian(Endian::Little)
                    .with_description("Retransmit timeout"),
                FieldDef::new("snd_mss", 128, 32, FieldType::Uint)
                    .with_endian(Endian::Little)
                    .with_description("Send MSS"),
            ])
    }

    fn sample_sockid() -> ProtocolDef {
        ProtocolDef::new("NL_Diag_SockID", 384).with_fields(vec![
            FieldDef::new("sport", 0, 16, FieldType::Uint)
                .with_endian(Endian::Big)
                .with_description("Source port"),
            FieldDef::new("dport", 16, 16, FieldType::Uint)
                .with_endian(Endian::Big)
                .with_description("Destination port"),
            FieldDef::new("src_ip", 32, 128, FieldType::Bytes)
                .with_description("Source IP"),
        ])
    }

    #[test]
    fn test_generate_bbrinfo_lua() {
        let proto = sample_bbrinfo();
        let output = generate_wireshark_lua_single(&proto);

        // Proto declaration
        assert!(output.contains("Proto(\"inet_diag_nl_diag_bbrinfo\""));
        // ProtoField declarations with correct types
        assert!(output.contains("ProtoField.uint32(\"inet_diag_nl_diag_bbrinfo.bbr_bw_lo\""));
        assert!(output.contains("ProtoField.uint32(\"inet_diag_nl_diag_bbrinfo.bbr_min_rtt\""));
        // 5 fields in fields table
        assert!(output.contains("proto_nl_diag_bbrinfo.fields = {"));
        // Dissector uses add_le for little-endian u32
        assert!(output.contains("add_le(f_nl_diag_bbrinfo_bbr_bw_lo, buffer(0, 4))"));
        assert!(output.contains("add_le(f_nl_diag_bbrinfo_bbr_cwnd_gain, buffer(16, 4))"));
        // Post-dissector registration
        assert!(output.contains("register_postdissector(proto_nl_diag_bbrinfo)"));
    }

    #[test]
    fn test_generate_tcpinfo_variable_guards() {
        let proto = sample_tcpinfo_short();
        let output = generate_wireshark_lua_single(&proto);

        // Variable-length protocol should have buffer length guards
        assert!(output.contains("if buffer:len() >= 1 then"));   // state at offset 0, size 1
        assert!(output.contains("if buffer:len() >= 12 then"));  // rto at offset 8, size 4
        assert!(output.contains("if buffer:len() >= 20 then"));  // snd_mss at offset 16, size 4
    }

    #[test]
    fn test_field_type_mapping() {
        assert_eq!(lua_proto_field(&FieldType::Uint, 8), ("ProtoField.uint8", ", base.DEC"));
        assert_eq!(lua_proto_field(&FieldType::Uint, 16), ("ProtoField.uint16", ", base.DEC"));
        assert_eq!(lua_proto_field(&FieldType::Uint, 32), ("ProtoField.uint32", ", base.DEC"));
        assert_eq!(lua_proto_field(&FieldType::Uint, 64), ("ProtoField.uint64", ", base.DEC"));
        assert_eq!(lua_proto_field(&FieldType::Sint, 32), ("ProtoField.int32", ", base.DEC"));
        assert_eq!(lua_proto_field(&FieldType::Flags, 8), ("ProtoField.uint8", ", base.HEX"));
        assert_eq!(lua_proto_field(&FieldType::Ipv4Addr, 32), ("ProtoField.ipv4", ""));
        assert_eq!(lua_proto_field(&FieldType::Ipv6Addr, 128), ("ProtoField.ipv6", ""));
        assert_eq!(lua_proto_field(&FieldType::Bytes, 64), ("ProtoField.bytes", ""));
    }

    #[test]
    fn test_endian_handling() {
        let proto = sample_sockid();
        let output = generate_wireshark_lua_single(&proto);

        // Big-endian ports should use add() not add_le()
        assert!(output.contains("subtree:add(f_nl_diag_sockid_sport, buffer(0, 2))"));
        assert!(output.contains("subtree:add(f_nl_diag_sockid_dport, buffer(2, 2))"));
    }

    #[test]
    fn test_aggregate_lua() {
        let bbr = sample_bbrinfo();
        let protos: Vec<(u16, &str, &ProtocolDef)> = vec![
            (16, "NL_Diag_BBRInfo", &bbr),
        ];
        let output = generate_wireshark_lua(&protos);

        // Should have aggregate post-dissector
        assert!(output.contains("proto_inet_diag_attrs"));
        assert!(output.contains("register_postdissector(proto_inet_diag_attrs)"));
        // Should dispatch on attribute type
        assert!(output.contains("if rta_type == 16 then"));
        // Should reference the BBRInfo proto
        assert!(output.contains("tree:add(proto_nl_diag_bbrinfo"));
    }
}
