//! Code generator: IR ProtocolDef → xdp2-rs ProtocolOps implementation.
//!
//! Generates Rust source files compatible with the xdp2-protocols crate,
//! using zerocopy for zero-copy header parsing and implementing the
//! ProtocolOps trait from xdp2-core.

use crate::ir::{Endian, FieldType, ProtocolDef};

use super::{canonical_to_pascal, canonical_to_snake, field_name_rust, rust_type_for_bits};

/// A single field in the generated zerocopy struct.
struct StructField {
    name: String,
    rust_type: String,
    comment: String,
    /// Accessor methods to generate (for bitfields or multi-byte fields).
    accessors: Vec<Accessor>,
}

/// An accessor method for a bitfield or endian-aware field.
struct Accessor {
    name: String,
    return_type: String,
    body: String,
}

/// Generate a complete xdp2-rs protocol module from a ProtocolDef.
pub fn generate_xdp2_rs(proto: &ProtocolDef) -> String {
    let pascal = canonical_to_pascal(&proto.name);
    let min_bytes = proto.min_header_bits / 8;

    let mut out = String::new();

    // Header comment
    out.push_str(&format!(
        "// Auto-generated by proto-audit from IR definition.\n\
         // Protocol: {}\n\
         // Minimum header: {} bytes\n\n",
        proto.name, min_bytes
    ));

    // Imports
    out.push_str("use xdp2_core::{ParseError, ProtocolOps};\n");
    out.push_str("use zerocopy::{FromBytes, Immutable, KnownLayout};\n\n");

    // Build struct fields from IR
    let (struct_fields, _has_bitfields) = build_struct_fields(proto);

    // Emit the zerocopy header struct
    out.push_str("#[derive(FromBytes, KnownLayout, Immutable, Debug)]\n");
    out.push_str("#[repr(C, packed)]\n");
    out.push_str(&format!("pub struct {}Header {{\n", pascal));

    for sf in &struct_fields {
        if !sf.comment.is_empty() {
            out.push_str(&format!("    /// {}\n", sf.comment));
        }
        out.push_str(&format!("    pub {}: {},\n", sf.name, sf.rust_type));
    }
    out.push_str("}\n\n");

    // Emit accessor methods if any exist
    let all_accessors: Vec<&Accessor> = struct_fields.iter().flat_map(|sf| &sf.accessors).collect();
    if !all_accessors.is_empty() {
        out.push_str(&format!("impl {}Header {{\n", pascal));
        for acc in &all_accessors {
            out.push_str(&format!(
                "    pub fn {}(&self) -> {} {{\n        {}\n    }}\n\n",
                acc.name, acc.return_type, acc.body
            ));
        }
        out.push_str("}\n\n");
    }

    // Emit the Ops struct and ProtocolOps impl
    out.push_str(&format!("pub struct {}Ops;\n\n", pascal));
    out.push_str(&format!("impl ProtocolOps for {}Ops {{\n", pascal));
    out.push_str(&format!("    const MIN_LEN: usize = {};\n", min_bytes));
    out.push_str(&format!("    const NAME: &'static str = \"{}\";\n", proto.name));

    // header_len — only override if variable length
    if proto.is_variable_length {
        if let Some(len_field) = proto.fields.iter().find(|f| f.is_length) {
            let byte_offset = len_field.offset_bits / 8;
            let multiplier = len_field.length_multiplier.unwrap_or(1);
            out.push_str("\n    #[inline]\n");
            out.push_str("    fn header_len(&self, hdr: &[u8], _maxlen: usize) -> Result<usize, ParseError> {\n");
            out.push_str(&format!(
                "        if hdr.len() < {} {{ return Err(ParseError::Length); }}\n",
                min_bytes
            ));

            if len_field.size_bits <= 8 {
                // Sub-byte or single-byte length field
                if len_field.size_bits < 8 {
                    // Bitfield length (e.g., IPv4 IHL in lower nibble)
                    let bit_in_byte = len_field.offset_bits % 8;
                    let mask = (1u32 << len_field.size_bits) - 1;
                    let shift = 8 - bit_in_byte - len_field.size_bits;
                    out.push_str(&format!(
                        "        let val = ((hdr[{}] >> {}) & 0x{:02x}) as usize;\n",
                        byte_offset, shift, mask
                    ));
                } else {
                    out.push_str(&format!(
                        "        let val = hdr[{}] as usize;\n",
                        byte_offset
                    ));
                }
            } else if len_field.size_bits == 16 {
                out.push_str(&format!(
                    "        let val = u16::from_be_bytes([hdr[{}], hdr[{}]]) as usize;\n",
                    byte_offset, byte_offset + 1
                ));
            } else {
                out.push_str(&format!(
                    "        let val = hdr[{}] as usize;\n",
                    byte_offset
                ));
            }

            if multiplier > 1 {
                out.push_str(&format!("        Ok(val * {})\n", multiplier));
            } else {
                out.push_str("        Ok(val)\n");
            }
            out.push_str("    }\n");
        }
    }

    // next_proto — dispatch or leaf
    out.push_str("\n    #[inline]\n");
    out.push_str("    fn next_proto(&self, hdr: &[u8]) -> Result<i32, ParseError> {\n");

    if let Some(ref dispatch_name) = proto.dispatch_field {
        if let Some(dispatch_field) = proto.fields.iter().find(|f| f.name == *dispatch_name) {
            let byte_offset = dispatch_field.offset_bits / 8;

            out.push_str(&format!(
                "        if hdr.len() < {} {{ return Err(ParseError::Length); }}\n",
                min_bytes
            ));

            if dispatch_field.size_bits <= 8 {
                if dispatch_field.size_bits < 8 {
                    let bit_in_byte = dispatch_field.offset_bits % 8;
                    let mask = (1u32 << dispatch_field.size_bits) - 1;
                    let shift = 8 - bit_in_byte - dispatch_field.size_bits;
                    out.push_str(&format!(
                        "        Ok(((hdr[{}] >> {}) & 0x{:02x}) as i32)\n",
                        byte_offset, shift, mask
                    ));
                } else {
                    out.push_str(&format!(
                        "        Ok(hdr[{}] as i32)\n",
                        byte_offset
                    ));
                }
            } else if dispatch_field.size_bits == 16 {
                out.push_str(&format!(
                    "        Ok(u16::from_be_bytes([hdr[{}], hdr[{}]]) as i32)\n",
                    byte_offset, byte_offset + 1
                ));
            } else if dispatch_field.size_bits == 32 {
                out.push_str(&format!(
                    "        Ok(u32::from_be_bytes([hdr[{}], hdr[{}], hdr[{}], hdr[{}]]) as i32)\n",
                    byte_offset, byte_offset + 1, byte_offset + 2, byte_offset + 3
                ));
            } else {
                out.push_str(&format!(
                    "        Ok(hdr[{}] as i32)\n",
                    byte_offset
                ));
            }
        } else {
            // Dispatch field named but not found in fields — treat as leaf
            out.push_str("        Err(ParseError::UnknownProto)\n");
        }
    } else {
        // Leaf protocol
        out.push_str("        Err(ParseError::UnknownProto)\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Tests
    out.push_str("#[cfg(test)]\n");
    out.push_str("mod tests {\n");
    out.push_str("    use super::*;\n\n");

    // Test: header_len returns MIN_LEN for fixed, or correct value for variable
    out.push_str(&format!(
        "    #[test]\n    fn {}_header_len() {{\n",
        canonical_to_snake(&proto.name)
    ));
    out.push_str(&format!(
        "        let hdr = [0u8; {}];\n",
        min_bytes.max(64) // ensure enough bytes for the test
    ));
    out.push_str(&format!("        let ops = {}Ops;\n", pascal));

    if proto.is_variable_length {
        out.push_str("        // Variable-length: result depends on header content\n");
        out.push_str("        assert!(ops.header_len(&hdr, 100).is_ok());\n");
    } else {
        out.push_str(&format!(
            "        assert_eq!(ops.header_len(&hdr, 100).unwrap(), {});\n",
            min_bytes
        ));
    }
    out.push_str("    }\n\n");

    // Test: next_proto behavior
    out.push_str(&format!(
        "    #[test]\n    fn {}_{} {{\n",
        canonical_to_snake(&proto.name),
        if proto.dispatch_field.is_some() {
            "dispatches()"
        } else {
            "is_leaf()"
        }
    ));
    out.push_str(&format!(
        "        let hdr = [0u8; {}];\n",
        min_bytes.max(64)
    ));
    out.push_str(&format!("        let ops = {}Ops;\n", pascal));

    if proto.dispatch_field.is_some() {
        out.push_str("        assert!(ops.next_proto(&hdr).is_ok());\n");
    } else {
        out.push_str("        assert!(matches!(\n");
        out.push_str("            ops.next_proto(&hdr),\n");
        out.push_str("            Err(ParseError::UnknownProto)\n");
        out.push_str("        ));\n");
    }
    out.push_str("    }\n");

    // Test: too-short slice
    out.push_str(&format!(
        "\n    #[test]\n    fn {}_rejects_short() {{\n",
        canonical_to_snake(&proto.name)
    ));
    if min_bytes > 1 {
        out.push_str(&format!("        let hdr = [0u8; {}];\n", min_bytes - 1));
        out.push_str(&format!("        let ops = {}Ops;\n", pascal));
        if proto.is_variable_length {
            out.push_str("        assert!(ops.header_len(&hdr, 100).is_err());\n");
        } else if proto.dispatch_field.is_some() {
            out.push_str("        assert!(ops.next_proto(&hdr).is_err());\n");
        } else {
            // Fixed-length leaf — default header_len always returns Ok(MIN_LEN)
            // but next_proto returns UnknownProto regardless of length
            out.push_str("        // Fixed-length leaf: header_len uses default (Ok(MIN_LEN))\n");
            out.push_str("        // but the caller checks bounds before calling\n");
        }
    } else {
        out.push_str("        // MIN_LEN is 1 byte, no shorter valid slice\n");
    }
    out.push_str("    }\n");

    out.push_str("}\n");

    out
}

/// Build zerocopy struct fields from IR field definitions.
///
/// Returns (struct_fields, has_bitfields).
fn build_struct_fields(proto: &ProtocolDef) -> (Vec<StructField>, bool) {
    let mut fields = Vec::new();
    let mut has_bitfields = false;

    // Group contiguous sub-byte fields into packed byte fields
    let mut i = 0;
    while i < proto.fields.len() {
        let field = &proto.fields[i];

        // Check for sub-byte bitfield group
        if field.size_bits < 8 && field.offset_bits % 8 == 0 {
            // Start of a bitfield group — collect all sub-byte fields in this byte
            let byte_start = field.offset_bits / 8;
            let mut group = vec![];
            let mut bits_total = 0u32;
            let mut j = i;
            while j < proto.fields.len() {
                let gf = &proto.fields[j];
                if gf.offset_bits / 8 != byte_start || (j > i && gf.size_bits >= 8) {
                    break;
                }
                if gf.size_bits == 0 {
                    j += 1;
                    continue;
                }
                group.push(gf);
                bits_total += gf.size_bits;
                j += 1;
                if bits_total >= 8 {
                    break;
                }
            }

            if group.len() > 1 {
                has_bitfields = true;
                let packed_type = rust_type_for_bits(bits_total);
                let comment_parts: Vec<String> = group
                    .iter()
                    .map(|f| format!("{}({}b)", f.name, f.size_bits))
                    .collect();

                let mut accessors = Vec::new();
                let mut bit_pos = 0u32;
                for gf in &group {
                    let mask = (1u32 << gf.size_bits) - 1;
                    let shift = bits_total - bit_pos - gf.size_bits;
                    accessors.push(Accessor {
                        name: field_name_rust(&gf.name),
                        return_type: "u8".to_string(),
                        body: format!(
                            "(self.{}_raw >> {}) & 0x{:02x}",
                            field_name_rust(&group[0].name),
                            shift,
                            mask
                        ),
                    });
                    bit_pos += gf.size_bits;
                }

                fields.push(StructField {
                    name: format!("{}_raw", field_name_rust(&group[0].name)),
                    rust_type: packed_type,
                    comment: format!("Packed: {}", comment_parts.join(" + ")),
                    accessors,
                });

                i = j;
                continue;
            }
            // Single sub-byte field at byte boundary — just use u8
        }

        // Sub-byte field not at byte boundary — skip (already in a group or padding)
        if field.size_bits < 8 && field.offset_bits % 8 != 0 {
            // Check if this is part of a group that started on a byte boundary
            // If not handled above, we have a misaligned bitfield — pack as raw byte
            i += 1;
            continue;
        }

        // Regular byte-aligned field
        if field.size_bits == 0 {
            i += 1;
            continue;
        }

        let (rust_type, accessors) = match field.field_type {
            FieldType::MacAddr if field.size_bits == 48 => {
                ("[u8; 6]".to_string(), vec![])
            }
            FieldType::Ipv4Addr if field.size_bits == 32 => {
                ("[u8; 4]".to_string(), vec![])
            }
            FieldType::Ipv6Addr if field.size_bits == 128 => {
                ("[u8; 16]".to_string(), vec![])
            }
            _ if field.size_bits == 8 => ("u8".to_string(), vec![]),
            _ if field.size_bits == 16 && matches!(field.endian, Endian::Big) => {
                // Use [u8; 2] for network-byte-order 16-bit fields
                let fname = field_name_rust(&field.name);
                let acc = Accessor {
                    name: fname.clone(),
                    return_type: "u16".to_string(),
                    body: format!(
                        "u16::from_be_bytes(self.{}_be)",
                        fname
                    ),
                };
                (format!("[u8; 2]"), vec![acc])
            }
            _ if field.size_bits == 32 && matches!(field.endian, Endian::Big) => {
                let fname = field_name_rust(&field.name);
                let acc = Accessor {
                    name: fname.clone(),
                    return_type: "u32".to_string(),
                    body: format!(
                        "u32::from_be_bytes(self.{}_be)",
                        fname
                    ),
                };
                (format!("[u8; 4]"), vec![acc])
            }
            _ if field.size_bits % 8 == 0 => {
                let bytes = field.size_bits / 8;
                if bytes <= 8 {
                    (rust_type_for_bits(field.size_bits), vec![])
                } else {
                    (format!("[u8; {}]", bytes), vec![])
                }
            }
            _ => {
                // Non-byte-aligned — use smallest containing type
                (rust_type_for_bits(field.size_bits), vec![])
            }
        };

        // Field name: add _be suffix for fields that have endian accessors
        let name = if !accessors.is_empty() && field.size_bits > 8 {
            format!("{}_be", field_name_rust(&field.name))
        } else {
            field_name_rust(&field.name)
        };

        fields.push(StructField {
            name,
            rust_type,
            comment: field.description.clone(),
            accessors,
        });

        i += 1;
    }

    (fields, has_bitfields)
}

/// Generate a batch of xdp2-rs protocol files for bundling as leaf protocols.
/// This generates a single file with multiple protocol structs (like storage/misc.rs).
pub fn generate_xdp2_rs_bundle(protos: &[&ProtocolDef]) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by proto-audit from IR definitions.\n");
    out.push_str("// Bundled leaf protocols.\n\n");
    out.push_str("use xdp2_core::{ParseError, ProtocolOps};\n");
    out.push_str("use zerocopy::{FromBytes, Immutable, KnownLayout};\n\n");

    for proto in protos {
        let pascal = canonical_to_pascal(&proto.name);
        let min_bytes = proto.min_header_bits / 8;

        // Header struct
        let (struct_fields, _) = build_struct_fields(proto);

        out.push_str(&format!("// --- {} ({} bytes) ---\n\n", proto.name, min_bytes));
        out.push_str("#[derive(FromBytes, KnownLayout, Immutable, Debug)]\n");
        out.push_str("#[repr(C, packed)]\n");
        out.push_str(&format!("pub struct {}Header {{\n", pascal));
        for sf in &struct_fields {
            if !sf.comment.is_empty() {
                out.push_str(&format!("    /// {}\n", sf.comment));
            }
            out.push_str(&format!("    pub {}: {},\n", sf.name, sf.rust_type));
        }
        out.push_str("}\n\n");

        // Ops struct
        out.push_str(&format!("pub struct {}Ops;\n\n", pascal));
        out.push_str(&format!("impl ProtocolOps for {}Ops {{\n", pascal));
        out.push_str(&format!("    const MIN_LEN: usize = {};\n", min_bytes));
        out.push_str(&format!("    const NAME: &'static str = \"{}\";\n\n", proto.name));
        out.push_str("    #[inline]\n");
        out.push_str("    fn next_proto(&self, _hdr: &[u8]) -> Result<i32, ParseError> {\n");
        out.push_str("        Err(ParseError::UnknownProto)\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    // Tests
    out.push_str("#[cfg(test)]\nmod tests {\n    use super::*;\n\n");
    for proto in protos {
        let pascal = canonical_to_pascal(&proto.name);
        let snake = canonical_to_snake(&proto.name);
        let min_bytes = proto.min_header_bits / 8;
        out.push_str(&format!(
            "    #[test]\n    fn {}_is_leaf() {{\n        assert!(matches!(\n            {}Ops.next_proto(&[0u8; {}]),\n            Err(ParseError::UnknownProto)\n        ));\n    }}\n\n",
            snake, pascal, min_bytes.max(1)
        ));
    }
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn sample_udp() -> ProtocolDef {
        ProtocolDef::new("UDP", 64).with_fields(vec![
            FieldDef::new("src_port", 0, 16, FieldType::Uint)
                .with_endian(Endian::Big)
                .with_description("Source port"),
            FieldDef::new("dst_port", 16, 16, FieldType::Uint)
                .with_endian(Endian::Big)
                .with_description("Destination port"),
            FieldDef::new("length", 32, 16, FieldType::Uint)
                .with_endian(Endian::Big)
                .with_description("Datagram length")
                .with_length(None),
            FieldDef::new("checksum", 48, 16, FieldType::Uint)
                .with_endian(Endian::Big)
                .with_description("Checksum"),
        ])
    }

    fn sample_ipv4() -> ProtocolDef {
        ProtocolDef::new("IPv4", 160)
            .with_variable_length()
            .with_dispatch_field("protocol")
            .with_fields(vec![
                FieldDef::new("version", 0, 4, FieldType::Uint)
                    .with_description("IP version"),
                FieldDef::new("ihl", 4, 4, FieldType::Uint)
                    .with_description("Header length in 32-bit words")
                    .with_length(Some(4)),
                FieldDef::new("tos", 8, 8, FieldType::Uint)
                    .with_description("Type of service"),
                FieldDef::new("total_length", 16, 16, FieldType::Uint)
                    .with_endian(Endian::Big)
                    .with_description("Total packet length"),
                FieldDef::new("identification", 32, 16, FieldType::Uint)
                    .with_endian(Endian::Big)
                    .with_description("Fragment ID"),
                FieldDef::new("flags", 48, 3, FieldType::Flags)
                    .with_description("IP flags"),
                FieldDef::new("fragment_offset", 51, 13, FieldType::Uint)
                    .with_endian(Endian::Big)
                    .with_description("Fragment offset"),
                FieldDef::new("ttl", 64, 8, FieldType::Uint)
                    .with_description("Time to live"),
                FieldDef::new("protocol", 72, 8, FieldType::Enum)
                    .with_description("Next-layer protocol")
                    .with_dispatch(),
                FieldDef::new("checksum", 80, 16, FieldType::Uint)
                    .with_endian(Endian::Big)
                    .with_description("Header checksum"),
                FieldDef::new("src_addr", 96, 32, FieldType::Ipv4Addr)
                    .with_endian(Endian::Big)
                    .with_description("Source address"),
                FieldDef::new("dst_addr", 128, 32, FieldType::Ipv4Addr)
                    .with_endian(Endian::Big)
                    .with_description("Destination address"),
            ])
    }

    fn sample_leaf() -> ProtocolDef {
        ProtocolDef::new("SCSI", 256).with_fields(vec![
            FieldDef::new("lun", 0, 64, FieldType::Bytes),
            FieldDef::new("crn", 64, 8, FieldType::Uint),
            FieldDef::new("task_attr", 72, 8, FieldType::Uint),
        ])
    }

    #[test]
    fn test_generate_xdp2_rs_udp() {
        let proto = sample_udp();
        let output = generate_xdp2_rs(&proto);

        assert!(output.contains("pub struct UDPHeader"));
        assert!(output.contains("#[derive(FromBytes, KnownLayout, Immutable, Debug)]"));
        assert!(output.contains("#[repr(C, packed)]"));
        assert!(output.contains("const MIN_LEN: usize = 8;"));
        assert!(output.contains("const NAME: &'static str = \"UDP\""));
        assert!(output.contains("Err(ParseError::UnknownProto)"));
    }

    #[test]
    fn test_generate_xdp2_rs_ipv4_dispatch() {
        let proto = sample_ipv4();
        let output = generate_xdp2_rs(&proto);

        assert!(output.contains("pub struct IPv4Header"));
        assert!(output.contains("const MIN_LEN: usize = 20;"));
        assert!(output.contains("const NAME: &'static str = \"IPv4\""));
        // Should have variable-length header_len
        assert!(output.contains("fn header_len"));
        // Should dispatch on protocol field at byte offset 9
        assert!(output.contains("hdr[9] as i32"));
    }

    #[test]
    fn test_generate_xdp2_rs_ipv4_bitfields() {
        let proto = sample_ipv4();
        let output = generate_xdp2_rs(&proto);

        // version(4) + ihl(4) should be packed into version_raw: u8
        assert!(output.contains("version_raw"));
        assert!(output.contains("Packed:"));
    }

    #[test]
    fn test_generate_xdp2_rs_leaf() {
        let proto = sample_leaf();
        let output = generate_xdp2_rs(&proto);

        assert!(output.contains("pub struct SCSIHeader"));
        assert!(output.contains("Err(ParseError::UnknownProto)"));
        assert!(output.contains("is_leaf()"));
    }

    #[test]
    fn test_generate_xdp2_rs_has_tests() {
        let proto = sample_udp();
        let output = generate_xdp2_rs(&proto);

        assert!(output.contains("#[cfg(test)]"));
        assert!(output.contains("#[test]"));
        assert!(output.contains("udp_header_len"));
    }

    #[test]
    fn test_generate_xdp2_rs_bundle() {
        let p1 = ProtocolDef::new("AoE", 80).with_fields(vec![
            FieldDef::new("ver_flags", 0, 8, FieldType::Uint),
            FieldDef::new("error", 8, 8, FieldType::Uint),
        ]);
        let p2 = ProtocolDef::new("iSER", 224).with_fields(vec![
            FieldDef::new("flags", 0, 8, FieldType::Uint),
        ]);
        let output = generate_xdp2_rs_bundle(&[&p1, &p2]);

        assert!(output.contains("pub struct AoEHeader"));
        assert!(output.contains("pub struct iSERHeader"));
        assert!(output.contains("AoEOps"));
        assert!(output.contains("iSEROps"));
        assert!(output.contains("aoe_is_leaf"));
        assert!(output.contains("iser_is_leaf"));
    }
}
