/* SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Auto-generated by proto-audit from IR definition.
 * Protocol: {{PROTO_NAME}}
 */

#ifndef {{GUARD}}
#define {{GUARD}}

#include <{{KERNEL_HEADER}}>

#include "xdp2/parser.h"

static inline int {{SNAKE}}_proto(const void *vhdr)
{
	return ((struct {{KERNEL_STRUCT}} *)vhdr)->{{DISPATCH_FIELD}};
}

{{#VARIABLE_LENGTH}}
static inline ssize_t {{SNAKE}}_length(const void *vhdr, size_t maxlen)
{
	return ((struct {{KERNEL_STRUCT}} *)vhdr)->{{LENGTH_FIELD}}{{LENGTH_MULTIPLIER}};
}
{{/VARIABLE_LENGTH}}

#endif /* {{GUARD}} */

#ifdef XDP2_DEFINE_PARSE_NODE

/* xdp2_parse_{{SNAKE}} protocol definition
 *
 * Parse {{PROTO_NAME}} header
 *
 * Next protocol operation returns protocol identifier
 */
static const struct xdp2_proto_def xdp2_parse_{{SNAKE}} __unused() = {
	.name = "{{PROTO_NAME}}",
	.min_len = sizeof(struct {{KERNEL_STRUCT}}),
{{#VARIABLE_LENGTH}}
	.ops.len = {{SNAKE}}_length,
{{/VARIABLE_LENGTH}}
	.ops.next_proto = {{SNAKE}}_proto,
};

#endif /* XDP2_DEFINE_PARSE_NODE */
