/* SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Auto-generated by proto-audit from IR definition.
 * Protocol: {{PROTO_NAME}}
 */

#ifndef {{GUARD}}
#define {{GUARD}}

#include <{{KERNEL_HEADER}}>

#include "xdp2/parser.h"

#endif /* {{GUARD}} */

#ifdef XDP2_DEFINE_PARSE_NODE

/* xdp2_parse_{{SNAKE}} protocol definition
 *
 * Parse {{PROTO_NAME}} header
 */
static const struct xdp2_proto_def xdp2_parse_{{SNAKE}} __unused() = {
	.name = "{{PROTO_NAME}}",
	.min_len = sizeof(struct {{KERNEL_STRUCT}}),
};

#endif /* XDP2_DEFINE_PARSE_NODE */
