//! Code generation module.
//!
//! ## C/C++ Cross-Reference
//!
//! | Rust Item | C/C++ Source | C/C++ Item |
//! |-----------|-------------|------------|
//! | `render_c` | `src/templates/xdp2/c_def.template.c` | C parser generation |
//! | `render_xdp` | `src/templates/xdp2/xdp_def.template.c` | XDP/eBPF parser generation |
//! | (Tera) | `python_generators.h` | Python/Pyrate template engine |
//!
//! ## Behavioral Differences
//! - Uses Tera (Jinja2-like) templates instead of Pyrate (Python-based).
//! - Template syntax: `{{ var }}`, `{% for %}`, `{% if %}` (Tera/Jinja2).

use std::collections::HashMap;

use petgraph::visit::EdgeRef;
use tera::{Context, Tera};

use crate::graph::ParseGraph;
use crate::ir::ParserDef;

/// Render context built from a ParseGraph for template rendering.
fn build_context(pg: &ParseGraph, parser: &ParserDef) -> Context {
    let mut ctx = Context::new();

    ctx.insert("parser_name", &parser.name);
    ctx.insert("root_node", &parser.root_node);
    ctx.insert("max_nodes", &parser.max_nodes);
    ctx.insert("max_encaps", &parser.max_encaps);
    ctx.insert("max_frames", &parser.max_frames);
    ctx.insert("frame_size", &parser.frame_size);
    ctx.insert("metameta_size", &parser.metameta_size);
    ctx.insert("num_counters", &parser.num_counters);
    ctx.insert("num_keys", &parser.num_keys);

    if let Some(ref t) = parser.okay_target {
        ctx.insert("okay_target", t);
    }
    if let Some(ref t) = parser.fail_target {
        ctx.insert("fail_target", t);
    }

    // Build node list for template iteration.
    let mut nodes: Vec<HashMap<String, serde_json::Value>> = Vec::new();
    for idx in pg.graph.node_indices() {
        let v = &pg.graph[idx];
        let mut node = HashMap::new();
        node.insert("name".into(), serde_json::json!(v.name));
        node.insert("min_hdr_length".into(), serde_json::json!(v.min_hdr_length));
        node.insert("overlay".into(), serde_json::json!(v.overlay));
        node.insert("encap".into(), serde_json::json!(v.encap));

        // Dispatch entries
        let edges: Vec<HashMap<String, serde_json::Value>> = pg
            .graph
            .edges(idx)
            .map(|e| {
                let mut entry = HashMap::new();
                entry.insert("key".into(), serde_json::json!(e.weight().key_str));
                entry.insert("key_value".into(), serde_json::json!(e.weight().key_value));
                entry.insert("node".into(), serde_json::json!(pg.graph[e.target()].name));
                entry
            })
            .collect();
        node.insert("edges".into(), serde_json::json!(edges));
        node.insert("is_leaf".into(), serde_json::json!(edges.is_empty()));

        if let Some(ref hl) = v.hdr_length {
            node.insert("hdr_length".into(), serde_json::json!({
                "field_off": hl.field_off,
                "field_len": hl.field_len,
                "mask": hl.mask,
                "shift": hl.shift,
                "multiplier": hl.multiplier,
                "add": hl.add,
            }));
        }

        if let Some(ref np) = v.next_proto {
            node.insert("next_proto".into(), serde_json::json!({
                "field_off": np.field_off,
                "field_len": np.field_len,
                "mask": np.mask,
            }));
        }

        nodes.push(node);
    }
    ctx.insert("nodes", &nodes);
    ctx
}

/// Default C parser template (minimal, proof-of-concept).
///
/// A full implementation would load this from a .tera file.
const C_TEMPLATE: &str = r#"/* Generated by xdp2-compiler (Rust) */
/* Parser: {{ parser_name }} */
/* Root: {{ root_node }} */
/* Max nodes: {{ max_nodes }}, Max encaps: {{ max_encaps }} */

#include <stdint.h>
#include <stddef.h>

{% for node in nodes %}
/* Node: {{ node.name }} (min_len={{ node.min_hdr_length }}{% if node.overlay %}, overlay{% endif %}{% if node.encap %}, encap{% endif %}) */
{% if not node.is_leaf %}
/* Dispatch: {% for e in node.edges %}{{ e.key }}->{{ e.node }} {% endfor %}*/
{% endif %}
{% endfor %}
"#;

/// Render a C parser from the parse graph.
///
/// Reimplements: `generate_root_parser_c()` in `python_generators.h`
pub fn render_c(pg: &ParseGraph, parser: &ParserDef) -> Result<String, tera::Error> {
    let mut tera = Tera::default();
    tera.add_raw_template("c_def.tera", C_TEMPLATE)?;
    let ctx = build_context(pg, parser);
    tera.render("c_def.tera", &ctx)
}

/// Default XDP/eBPF parser template (minimal, proof-of-concept).
const XDP_TEMPLATE: &str = r#"/* Generated by xdp2-compiler (Rust) — XDP target */
/* Parser: {{ parser_name }} */
/* Root: {{ root_node }} */

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

{% for node in nodes %}
/* Node: {{ node.name }} (min_len={{ node.min_hdr_length }}{% if node.encap %}, encap{% endif %}) */
{% endfor %}
"#;

/// Render an XDP/eBPF parser from the parse graph.
///
/// Reimplements: `generate_root_parser_xdp_c()` in `python_generators.h`
pub fn render_xdp(pg: &ParseGraph, parser: &ParserDef) -> Result<String, tera::Error> {
    let mut tera = Tera::default();
    tera.add_raw_template("xdp_def.tera", XDP_TEMPLATE)?;
    let ctx = build_context(pg, parser);
    tera.render("xdp_def.tera", &ctx)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::ParserIr;

    fn sample_graph() -> (ParseGraph, ParserDef) {
        let ir = ParserIr::from_json(r#"{
            "parsers": [{"name": "test_parser", "root-node": "eth"}],
            "parse-nodes": [
                {"name": "eth", "min-hdr-length": 14, "next-proto": {
                    "field-off": 12, "field-len": 2,
                    "ents": [{"key": "0x0800", "node": "ipv4"}]
                }},
                {"name": "ipv4", "min-hdr-length": 20}
            ]
        }"#)
        .unwrap();
        let parser = ir.parsers[0].clone();
        let g = ParseGraph::from_ir(&ir);
        (g, parser)
    }

    #[test]
    fn render_c_output() {
        let (g, p) = sample_graph();
        let out = render_c(&g, &p).unwrap();
        assert!(out.contains("test_parser"));
        assert!(out.contains("eth"));
        assert!(out.contains("ipv4"));
        assert!(out.contains("0x0800"));
    }

    #[test]
    fn render_xdp_output() {
        let (g, p) = sample_graph();
        let out = render_xdp(&g, &p).unwrap();
        assert!(out.contains("test_parser"));
        assert!(out.contains("bpf_helpers"));
    }
}
