//! Code generation module.
//!
//! ## C/C++ Cross-Reference
//!
//! | Rust Item | C/C++ Source | C/C++ Item |
//! |-----------|-------------|------------|
//! | `render_c` | `src/templates/xdp2/c_def.template.c` | C parser generation |
//! | `render_xdp` | `src/templates/xdp2/xdp_def.template.c` | XDP/eBPF parser generation |
//! | (Tera) | `python_generators.h` | Python/Pyrate template engine |
//!
//! ## Behavioral Differences
//! - Uses Tera (Jinja2-like) templates instead of Pyrate (Python-based).
//! - Template syntax: `{{ var }}`, `{% for %}`, `{% if %}` (Tera/Jinja2).

use std::collections::HashMap;

use petgraph::visit::EdgeRef;
use tera::{Context, Tera};

use crate::graph::ParseGraph;
use crate::ir::ParserDef;

/// Render context built from a ParseGraph for template rendering.
fn build_context(pg: &ParseGraph, parser: &ParserDef) -> Context {
    let mut ctx = Context::new();

    ctx.insert("parser_name", &parser.name);
    ctx.insert("root_node", &parser.root_node);
    ctx.insert("max_nodes", &parser.max_nodes);
    ctx.insert("max_encaps", &parser.max_encaps);
    ctx.insert("max_frames", &parser.max_frames);
    ctx.insert("frame_size", &parser.frame_size);
    ctx.insert("metameta_size", &parser.metameta_size);
    ctx.insert("num_counters", &parser.num_counters);
    ctx.insert("num_keys", &parser.num_keys);

    if let Some(ref t) = parser.okay_target {
        ctx.insert("okay_target", t);
    }
    if let Some(ref t) = parser.fail_target {
        ctx.insert("fail_target", t);
    }

    // Build node list for template iteration.
    let mut nodes: Vec<HashMap<String, serde_json::Value>> = Vec::new();
    for idx in pg.graph.node_indices() {
        let v = &pg.graph[idx];
        let mut node = HashMap::new();
        node.insert("name".into(), serde_json::json!(v.name));
        node.insert("min_hdr_length".into(), serde_json::json!(v.min_hdr_length));
        node.insert("overlay".into(), serde_json::json!(v.overlay));
        node.insert("encap".into(), serde_json::json!(v.encap));

        // Dispatch entries
        let edges: Vec<HashMap<String, serde_json::Value>> = pg
            .graph
            .edges(idx)
            .map(|e| {
                let mut entry = HashMap::new();
                entry.insert("key".into(), serde_json::json!(e.weight().key_str));
                entry.insert("key_value".into(), serde_json::json!(e.weight().key_value));
                entry.insert("node".into(), serde_json::json!(pg.graph[e.target()].name));
                entry
            })
            .collect();
        node.insert("edges".into(), serde_json::json!(edges));
        node.insert("is_leaf".into(), serde_json::json!(edges.is_empty()));

        if let Some(ref hl) = v.hdr_length {
            node.insert(
                "hdr_length".into(),
                serde_json::json!({
                    "field_off": hl.field_off,
                    "field_len": hl.field_len,
                    "mask": hl.mask,
                    "shift": hl.shift,
                    "multiplier": hl.multiplier,
                    "add": hl.add,
                }),
            );
        }

        if let Some(ref np) = v.next_proto {
            node.insert(
                "next_proto".into(),
                serde_json::json!({
                    "field_off": np.field_off,
                    "field_len": np.field_len,
                    "mask": np.mask,
                }),
            );
        }

        nodes.push(node);
    }
    ctx.insert("nodes", &nodes);
    ctx
}

/// Default C parser template (minimal, proof-of-concept).
///
/// A full implementation would load this from a .tera file.
const C_TEMPLATE: &str = r#"/* Generated by xdp2-compiler (Rust) */
/* Parser: {{ parser_name }} */
/* Root: {{ root_node }} */
/* Max nodes: {{ max_nodes }}, Max encaps: {{ max_encaps }} */

#include <stdint.h>
#include <stddef.h>

{% for node in nodes %}
/* Node: {{ node.name }} (min_len={{ node.min_hdr_length }}{% if node.overlay %}, overlay{% endif %}{% if node.encap %}, encap{% endif %}) */
{% if not node.is_leaf %}
/* Dispatch: {% for e in node.edges %}{{ e.key }}->{{ e.node }} {% endfor %}*/
{% endif %}
{% endfor %}
"#;

/// Render a C parser from the parse graph.
///
/// Reimplements: `generate_root_parser_c()` in `python_generators.h`
pub fn render_c(pg: &ParseGraph, parser: &ParserDef) -> Result<String, tera::Error> {
    let mut tera = Tera::default();
    tera.add_raw_template("c_def.tera", C_TEMPLATE)?;
    let ctx = build_context(pg, parser);
    tera.render("c_def.tera", &ctx)
}

/// Default XDP/eBPF parser template (minimal, proof-of-concept).
const XDP_TEMPLATE: &str = r#"/* Generated by xdp2-compiler (Rust) — XDP target */
/* Parser: {{ parser_name }} */
/* Root: {{ root_node }} */

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

{% for node in nodes %}
/* Node: {{ node.name }} (min_len={{ node.min_hdr_length }}{% if node.encap %}, encap{% endif %}) */
{% endfor %}
"#;

/// Render an XDP/eBPF parser from the parse graph.
///
/// Reimplements: `generate_root_parser_xdp_c()` in `python_generators.h`
pub fn render_xdp(pg: &ParseGraph, parser: &ParserDef) -> Result<String, tera::Error> {
    let mut tera = Tera::default();
    tera.add_raw_template("xdp_def.tera", XDP_TEMPLATE)?;
    let ctx = build_context(pg, parser);
    tera.render("xdp_def.tera", &ctx)
}

// ── Rust codegen ─────────────────────────────────────────────────────

pub mod rust_gen {
    //! Rust monomorphic parser code generation.
    //!
    //! Generates a self-contained Rust module that parses packets using
    //! direct byte reads at IR-defined offsets. The output mirrors the
    //! structure of `graph_mono.rs` from `xdp2-bench`: one `parse_<node>()`
    //! function per protocol, `match`-based dispatch (compiles to jump
    //! tables), and depth-limited recursion for cyclic subgraphs.
    //!
    //! ## Design
    //!
    //! The generated code uses only `xdp2_core::ParseError` — it does NOT
    //! depend on `xdp2-protocols`. All field extraction (header length,
    //! next-proto) is inlined from the IR's `HdrLengthDef`/`NextProtoDef`.
    //!
    //! Step 8 of the performance plan confirmed that LLVM fully optimizes
    //! the ProtocolOps zero-cost abstractions, producing identical assembly
    //! to hand-written byte reads. The generated code is therefore written
    //! for clarity (named functions, comments) rather than micro-optimization.

    use std::collections::HashSet;
    use std::fmt::Write;

    use petgraph::visit::EdgeRef;

    use crate::graph::ParseGraph;
    use crate::ir::{HdrLengthDef, ParserDef};

    /// Generate a complete Rust parser module from the parse graph.
    pub fn render(pg: &ParseGraph, parser: &ParserDef) -> String {
        let mut out = String::with_capacity(4096);

        // Identify leaf nodes and cyclic nodes.
        let leaf_set: HashSet<String> = pg
            .leaf_nodes()
            .into_iter()
            .map(|idx| pg.graph[idx].name.clone())
            .collect();

        let has_cycles = pg.has_cycles();

        // Header
        writeln!(
            out,
            "//! Auto-generated monomorphic parser: {}",
            parser.name
        )
        .unwrap();
        writeln!(out, "//!").unwrap();
        writeln!(out, "//! Generated by xdp2-compiler from Parser IR.").unwrap();
        writeln!(out, "//! Do not edit — regenerate from the IR source.").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "use xdp2_core::ParseError;").unwrap();
        writeln!(out).unwrap();

        if has_cycles {
            writeln!(
                out,
                "/// Maximum parse depth (prevents infinite recursion in cyclic graphs)."
            )
            .unwrap();
            writeln!(out, "const MAX_DEPTH: u32 = {};", parser.max_nodes).unwrap();
            writeln!(out).unwrap();
        }

        // Entry point
        writeln!(out, "/// Parse one packet through the generated graph.").unwrap();
        writeln!(out, "#[inline]").unwrap();
        writeln!(
            out,
            "pub fn parse_packet(pkt: &[u8]) -> Result<(), ParseError> {{"
        )
        .unwrap();
        if has_cycles {
            writeln!(out, "    parse_{}(pkt, 0)", sanitize(&parser.root_node)).unwrap();
        } else {
            writeln!(out, "    parse_{}(pkt)", sanitize(&parser.root_node)).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Generate a function for each node.
        for idx in pg.graph.node_indices() {
            let v = &pg.graph[idx];
            let name = sanitize(&v.name);
            let is_leaf = leaf_set.contains(&v.name);
            let edges: Vec<_> = pg.graph.edges(idx).collect();

            if is_leaf {
                emit_leaf_fn(&mut out, &name, v.min_hdr_length);
            } else {
                emit_parse_fn(
                    &mut out,
                    pg,
                    &name,
                    v.min_hdr_length,
                    v.hdr_length.as_ref(),
                    v.next_proto.as_ref(),
                    &edges,
                    &leaf_set,
                    has_cycles,
                );
            }
        }

        out
    }

    /// Emit a leaf node function (length check only).
    fn emit_leaf_fn(out: &mut String, name: &str, min_len: usize) {
        writeln!(out, "#[inline]").unwrap();
        writeln!(
            out,
            "fn parse_{name}(pkt: &[u8]) -> Result<(), ParseError> {{"
        )
        .unwrap();
        writeln!(
            out,
            "    if pkt.len() < {min_len} {{ return Err(ParseError::Length); }}"
        )
        .unwrap();
        writeln!(out, "    Ok(())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    /// Emit a non-leaf parse function with header extraction and dispatch.
    fn emit_parse_fn(
        out: &mut String,
        pg: &ParseGraph,
        name: &str,
        min_len: usize,
        hdr_length: Option<&HdrLengthDef>,
        next_proto: Option<&crate::ir::NextProtoDef>,
        edges: &[petgraph::graph::EdgeReference<crate::graph::EdgeProp>],
        leaf_set: &HashSet<String>,
        has_cycles: bool,
    ) {
        // Function signature
        if has_cycles {
            writeln!(
                out,
                "fn parse_{name}(pkt: &[u8], depth: u32) -> Result<(), ParseError> {{"
            )
            .unwrap();
            writeln!(
                out,
                "    if depth >= MAX_DEPTH {{ return Err(ParseError::MaxNodes); }}"
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "fn parse_{name}(pkt: &[u8]) -> Result<(), ParseError> {{"
            )
            .unwrap();
        }

        // Length check
        writeln!(
            out,
            "    if pkt.len() < {min_len} {{ return Err(ParseError::Length); }}"
        )
        .unwrap();

        // Header length extraction
        if let Some(hl) = hdr_length {
            writeln!(out, "    // Variable-length header").unwrap();
            emit_hdr_len_extraction(out, hl);
            writeln!(
                out,
                "    if hlen < {min_len} || hlen > pkt.len() {{ return Err(ParseError::Length); }}"
            )
            .unwrap();
        } else {
            writeln!(out, "    let hlen = {};", min_len).unwrap();
        }

        // Next-proto extraction and dispatch
        if let Some(np) = next_proto {
            emit_next_proto_extraction(out, np);
            writeln!(out, "    let rest = &pkt[hlen..];").unwrap();

            // Match dispatch
            writeln!(out, "    match next {{").unwrap();
            for edge in edges {
                let target_name = &pg.graph[edge.target()].name;
                let target_sanitized = sanitize(target_name);
                let key = edge.weight().key_value;
                let is_target_leaf = leaf_set.contains(target_name);

                // Use hex for values >= 256 (ethertypes) for readability
                let key_str = if key >= 256 {
                    format!("{key:#06x}")
                } else {
                    format!("{key}")
                };

                if is_target_leaf || !has_cycles {
                    writeln!(out, "        {key_str} => parse_{target_sanitized}(rest),").unwrap();
                } else {
                    writeln!(
                        out,
                        "        {key_str} => parse_{target_sanitized}(rest, depth + 1),"
                    )
                    .unwrap();
                }
            }
            writeln!(out, "        _ => Err(ParseError::UnknownProto),").unwrap();
            writeln!(out, "    }}").unwrap();
        } else {
            writeln!(out, "    Ok(())").unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    /// Emit header length field extraction from `HdrLengthDef`.
    ///
    /// Builds the expression: `(read_field & mask >> shift) * mult + add`.
    /// Elides identity operations (mask=all-ones, shift=0, mult=1, add=0)
    /// to keep the generated code clean.
    fn emit_hdr_len_extraction(out: &mut String, hl: &HdrLengthDef) {
        let has_mask = hl.mask.is_some();
        let has_shift = hl.shift.map_or(false, |s| s > 0);
        let mult = hl.multiplier;
        let add = hl.add.unwrap_or(0);

        // Build up the expression as a string, eliding no-ops
        let read_expr = match hl.field_len {
            1 => format!("pkt[{}] as usize", hl.field_off),
            2 => format!(
                "u16::from_be_bytes([pkt[{}], pkt[{}]]) as usize",
                hl.field_off,
                hl.field_off + 1
            ),
            4 => format!(
                "u32::from_be_bytes([pkt[{}], pkt[{}], pkt[{}], pkt[{}]]) as usize",
                hl.field_off,
                hl.field_off + 1,
                hl.field_off + 2,
                hl.field_off + 3,
            ),
            _ => format!("pkt[{}] as usize", hl.field_off),
        };

        // Apply mask
        let after_mask = if let Some(ref mask_str) = hl.mask {
            let mask_val = parse_int(mask_str);
            format!("({read_expr} & {mask_val})")
        } else {
            read_expr
        };

        // Apply shift
        let after_shift = if has_shift {
            format!("({after_mask} >> {})", hl.shift.unwrap())
        } else {
            after_mask
        };

        // Apply multiplier and addend
        let hlen_expr = match (mult, add) {
            (1, 0) => after_shift,
            (m, 0) => {
                if has_mask || has_shift {
                    format!("{after_shift} * {m}")
                } else {
                    format!("{after_shift} * {m}")
                }
            }
            (1, a) => format!("{after_shift} + {a}"),
            (m, a) => format!("{after_shift} * {m} + {a}"),
        };

        writeln!(out, "    let hlen = {hlen_expr};").unwrap();
    }

    /// Emit next-protocol field extraction from `NextProtoDef`.
    fn emit_next_proto_extraction(out: &mut String, np: &crate::ir::NextProtoDef) {
        match np.field_len {
            1 => writeln!(out, "    let next = pkt[{}] as i64;", np.field_off).unwrap(),
            2 => writeln!(
                out,
                "    let next = u16::from_be_bytes([pkt[{}], pkt[{}]]) as i64;",
                np.field_off,
                np.field_off + 1
            )
            .unwrap(),
            4 => writeln!(
                out,
                "    let next = u32::from_be_bytes([pkt[{}], pkt[{}], pkt[{}], pkt[{}]]) as i64;",
                np.field_off,
                np.field_off + 1,
                np.field_off + 2,
                np.field_off + 3,
            )
            .unwrap(),
            _ => writeln!(out, "    let next = pkt[{}] as i64;", np.field_off).unwrap(),
        }

        // Apply mask if present
        if let Some(ref mask_str) = np.mask {
            let mask_val = parse_int(mask_str);
            writeln!(out, "    let next = next & {mask_val};").unwrap();
        }
    }

    /// Sanitize a node name to a valid Rust identifier.
    fn sanitize(name: &str) -> String {
        name.replace('-', "_").replace('.', "_")
    }

    /// Parse an integer from a string (handles hex "0xf" and decimal).
    fn parse_int(s: &str) -> usize {
        let s = s.trim();
        if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
            usize::from_str_radix(hex, 16).unwrap_or(0)
        } else {
            s.parse().unwrap_or(0)
        }
    }
}

/// Render a Rust monomorphic parser from the parse graph.
///
/// Generates a complete, self-contained Rust module that depends only on
/// `xdp2_core::ParseError`. See `rust_gen` module for details.
pub fn render_rust(pg: &ParseGraph, parser: &ParserDef) -> String {
    rust_gen::render(pg, parser)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::ParserIr;

    fn sample_graph() -> (ParseGraph, ParserDef) {
        let ir = ParserIr::from_json(
            r#"{
            "parsers": [{"name": "test_parser", "root-node": "eth"}],
            "parse-nodes": [
                {"name": "eth", "min-hdr-length": 14, "next-proto": {
                    "field-off": 12, "field-len": 2,
                    "ents": [{"key": "0x0800", "node": "ipv4"}]
                }},
                {"name": "ipv4", "min-hdr-length": 20}
            ]
        }"#,
        )
        .unwrap();
        let parser = ir.parsers[0].clone();
        let g = ParseGraph::from_ir(&ir);
        (g, parser)
    }

    #[test]
    fn render_c_output() {
        let (g, p) = sample_graph();
        let out = render_c(&g, &p).unwrap();
        assert!(out.contains("test_parser"));
        assert!(out.contains("eth"));
        assert!(out.contains("ipv4"));
        assert!(out.contains("0x0800"));
    }

    #[test]
    fn render_rust_output() {
        let (g, p) = sample_graph();
        let out = render_rust(&g, &p);
        // Should contain the entry point
        assert!(out.contains("pub fn parse_packet(pkt: &[u8])"));
        // Should contain parse functions for each node
        assert!(out.contains("fn parse_eth("));
        assert!(out.contains("fn parse_ipv4("));
        // Should contain dispatch key for 0x0800 in hex
        assert!(out.contains("0x0800"));
        // ipv4 is a leaf in this simple graph (no next-proto)
        assert!(out.contains("if pkt.len() < 20"));
        // eth has next-proto at offset 12, 2 bytes
        assert!(out.contains("u16::from_be_bytes"));
    }

    #[test]
    fn render_rust_bench_graph() {
        let ir = ParserIr::from_json(
            &std::fs::read_to_string(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/testdata/bench-graph.json"
            ))
            .unwrap(),
        )
        .unwrap();
        let parser = ir.parsers[0].clone();
        let g = ParseGraph::from_ir(&ir);
        let out = render_rust(&g, &parser);

        // Should have cycle detection (VLAN↔Ethernet, IPv6 EH chains)
        assert!(out.contains("MAX_DEPTH"));
        assert!(out.contains("depth: u32"));
        assert!(out.contains("depth + 1"));

        // Should have all 15 node functions
        assert!(out.contains("fn parse_ethernet("));
        assert!(out.contains("fn parse_vlan("));
        assert!(out.contains("fn parse_ipv4("));
        assert!(out.contains("fn parse_ipv6("));
        assert!(out.contains("fn parse_tcp("));
        assert!(out.contains("fn parse_ah("));
        assert!(out.contains("fn parse_ipv6_eh("));
        assert!(out.contains("fn parse_ipv6_frag("));

        // Ethertype keys should be hex
        assert!(out.contains("0x0800 => parse_ipv4("));
        assert!(out.contains("0x86dd => parse_ipv6("));
        assert!(out.contains("0x8100 => parse_vlan("));

        // IPv4 IHL: (pkt[0] & 0xf) * 4
        assert!(out.contains("(pkt[0] as usize & 15) * 4"));
        // IPv6 EH: pkt[1] * 8 + 8
        assert!(out.contains("pkt[1] as usize * 8 + 8"));
        // AH: pkt[1] * 4 + 8
        assert!(out.contains("pkt[1] as usize * 4 + 8"));
    }

    #[test]
    fn render_xdp_output() {
        let (g, p) = sample_graph();
        let out = render_xdp(&g, &p).unwrap();
        assert!(out.contains("test_parser"));
        assert!(out.contains("bpf_helpers"));
    }
}
