//! CLI binary for the XDP2 Rust compiler.
//!
//! Reads JSON Parser IR (from the C++ xdp2-compiler or hand-written),
//! builds the parse graph, and generates output in various formats.
//!
//! ## Usage
//!
//! ```bash
//! xdp2-rs-compiler --input parser.json --output-dot parser.dot
//! xdp2-rs-compiler --input parser.json --output-json roundtrip.json
//! xdp2-rs-compiler --input parser.json --output-c parser.p.c --output-xdp parser.xdp.h
//! ```
//!
//! ## C/C++ Cross-Reference
//!
//! | Rust Item | C/C++ Source | C/C++ Item |
//! |-----------|-------------|------------|
//! | `main()` | `src/tools/compiler/src/main.cpp` | `main()` — CLI entry point |
//! | `--input` | `-i parser.c` | Input file (JSON IR vs C source) |
//! | `--output-dot` | `-o parser.dot` | Graphviz DOT output |
//! | `--output-json` | `-o parser.json` | JSON IR output |
//! | `--output-c` | `-o parser.p.c` | C parser code generation |
//! | `--output-xdp` | `-o parser.xdp.h` | XDP/eBPF code generation |
//!
//! ## Behavioral Differences
//! - Reads JSON IR instead of C source (no Clang AST dependency).
//! - Includes optional `--compat` flag to normalize C++ JSON field names.

use std::fs;
use std::process;

use clap::Parser;

use xdp2_compiler::codegen;
use xdp2_compiler::compat;
use xdp2_compiler::dot;
use xdp2_compiler::graph::ParseGraph;
use xdp2_compiler::ir::ParserIr;

#[derive(Parser)]
#[command(
    name = "xdp2-rs-compiler",
    about = "XDP2 Rust compiler — JSON IR to parse graph and code generation",
    version
)]
struct Cli {
    /// Input JSON IR file.
    #[arg(short, long)]
    input: String,

    /// Apply C++ JSON compatibility normalization before parsing.
    /// Use this when the input was generated by the C++ xdp2-compiler.
    #[arg(long, default_value_t = false)]
    compat: bool,

    /// Output Graphviz DOT file.
    #[arg(long)]
    output_dot: Option<String>,

    /// Output C parser file.
    #[arg(long)]
    output_c: Option<String>,

    /// Output XDP/eBPF parser file.
    #[arg(long)]
    output_xdp: Option<String>,

    /// Output JSON IR file (roundtrip).
    #[arg(long)]
    output_json: Option<String>,

    /// Output Rust monomorphic parser file.
    #[arg(long)]
    output_rust: Option<String>,
}

fn main() {
    let cli = Cli::parse();

    // Read input JSON.
    let raw_json = match fs::read_to_string(&cli.input) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read '{}': {}", cli.input, e);
            process::exit(1);
        }
    };

    // Optionally normalize C++ JSON field names.
    let json = if cli.compat {
        match compat::normalize_cpp_json(&raw_json) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("error: compat normalization failed: {}", e);
                process::exit(1);
            }
        }
    } else {
        raw_json
    };

    // Parse IR.
    let ir = match ParserIr::from_json(&json) {
        Ok(ir) => ir,
        Err(e) => {
            eprintln!("error: failed to parse JSON IR from '{}': {}", cli.input, e);
            process::exit(1);
        }
    };

    // Build parse graph.
    let pg = ParseGraph::from_ir(&ir);

    eprintln!(
        "Loaded: {} parsers, {} nodes, {} edges",
        ir.parsers.len(),
        pg.node_count(),
        pg.edge_count(),
    );

    // Generate DOT output.
    if let Some(ref path) = cli.output_dot {
        let dot_str = dot::to_dot(&pg);
        if let Err(e) = fs::write(path, &dot_str) {
            eprintln!("error: cannot write '{}': {}", path, e);
            process::exit(1);
        }
        eprintln!("Wrote DOT: {}", path);
    }

    // Generate C parser output.
    if let Some(ref path) = cli.output_c {
        let parser = ir.parsers.first().unwrap_or_else(|| {
            eprintln!("error: no parser definition in IR");
            process::exit(1);
        });
        match codegen::render_c(&pg, parser) {
            Ok(code) => {
                if let Err(e) = fs::write(path, &code) {
                    eprintln!("error: cannot write '{}': {}", path, e);
                    process::exit(1);
                }
                eprintln!("Wrote C parser: {}", path);
            }
            Err(e) => {
                eprintln!("error: C codegen failed: {}", e);
                process::exit(1);
            }
        }
    }

    // Generate XDP/eBPF parser output.
    if let Some(ref path) = cli.output_xdp {
        let parser = ir.parsers.first().unwrap_or_else(|| {
            eprintln!("error: no parser definition in IR");
            process::exit(1);
        });
        match codegen::render_xdp(&pg, parser) {
            Ok(code) => {
                if let Err(e) = fs::write(path, &code) {
                    eprintln!("error: cannot write '{}': {}", path, e);
                    process::exit(1);
                }
                eprintln!("Wrote XDP parser: {}", path);
            }
            Err(e) => {
                eprintln!("error: XDP codegen failed: {}", e);
                process::exit(1);
            }
        }
    }

    // Generate Rust monomorphic parser output.
    if let Some(ref path) = cli.output_rust {
        let parser = ir.parsers.first().unwrap_or_else(|| {
            eprintln!("error: no parser definition in IR");
            process::exit(1);
        });
        let code = codegen::render_rust(&pg, parser);
        if let Err(e) = fs::write(path, &code) {
            eprintln!("error: cannot write '{}': {}", path, e);
            process::exit(1);
        }
        eprintln!("Wrote Rust parser: {}", path);
    }

    // Generate JSON IR output (roundtrip).
    if let Some(ref path) = cli.output_json {
        match ir.to_json() {
            Ok(json_out) => {
                if let Err(e) = fs::write(path, &json_out) {
                    eprintln!("error: cannot write '{}': {}", path, e);
                    process::exit(1);
                }
                eprintln!("Wrote JSON IR: {}", path);
            }
            Err(e) => {
                eprintln!("error: JSON serialization failed: {}", e);
                process::exit(1);
            }
        }
    }
}
