#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause-FreeBSD
"""aggregate-afxdp — roll up live-wire AF_XDP per-cell JSONs.

Walks `--results <root>` for cell JSONs matching the layout written
by `flow-dissector-afxdp-live` (Phase L1+):

  <root>/<date>/<testbed>/afxdp/<mode>/<size>b/<L>mpps.json

Emits two files under `--out` (default = --results):

  summary-afxdp.md   — markdown table with rows = (mode, size_b),
                       columns per offered load. ns/pkt + Mpps per cell.
  summary-afxdp.csv  — flat row-per-cell:
                       testbed, host, mode, frame_size_b, offered_mpps,
                       pps_received, mpps_received, ns_per_pkt,
                       drops_pct, zerocopy.

Distinct from `aggregate-results.py` because the AF_XDP campaign
measures a different shape (live-wire receive sweep, not per-pcap
PCAP replay) and the column sets diverge enough that one CSV gets
ugly fast.

Stdlib only.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

CSV_COLUMNS = [
    "testbed", "target", "mode", "frame_size_b",
    "offered_mpps", "pps_received", "mpps_received",
    "ns_per_pkt", "drops_pct", "zerocopy", "bench_log",
]


def collect(results_root: Path) -> list[dict]:
    """Return list of cell-record dicts, one per *mpps.json under
    <results_root>/<date>/<testbed>/afxdp/<mode>/<size>b/."""
    cells = []
    # rglob the whole tree; filter to JSONs that live inside afxdp/<mode>/<size>b/.
    for json_path in results_root.rglob("*.json"):
        # Path components: ... / afxdp / <mode> / <size>b / <L>mpps.json
        parts = json_path.parts
        if len(parts) < 4 or parts[-4] != "afxdp":
            continue
        size_dir = parts[-2]
        if not size_dir.endswith("b"):
            continue
        try:
            with json_path.open() as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warn: skipping {json_path}: {exc}", file=sys.stderr)
            continue
        # Need at minimum mode + offered_mpps to be useful.
        if "mode" not in data or "offered_mpps" not in data:
            continue
        data["_path"] = str(json_path)
        cells.append(data)
    cells.sort(key=lambda c: (c.get("testbed", ""), c.get("mode", ""),
                              c.get("frame_size_b", 0), c.get("offered_mpps", 0)))
    return cells


def fmt_num(x, d: int = 1) -> str:
    if x is None:
        return "—"
    if isinstance(x, float):
        return f"{x:.{d}f}"
    return str(x)


def write_csv(out_path: Path, cells: list[dict]) -> None:
    with out_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        w.writeheader()
        for c in cells:
            w.writerow({col: c.get(col, "") for col in CSV_COLUMNS})


def write_md(out_path: Path, cells: list[dict]) -> None:
    """Markdown rendering: per (testbed, frame_size) section, rows =
    mode, columns = offered load. Each cell shows ns/pkt + Mpps."""
    by_section = defaultdict(lambda: defaultdict(dict))
    loads_per_section = defaultdict(set)
    modes_per_section = defaultdict(set)
    for c in cells:
        key = (c.get("testbed", "?"), c.get("frame_size_b", 0))
        by_section[key][c["mode"]][c["offered_mpps"]] = c
        loads_per_section[key].add(c["offered_mpps"])
        modes_per_section[key].add(c["mode"])

    lines = [
        "# Live-Wire AF_XDP Performance Comparison",
        "",
        "Generated by `aggregate-afxdp.py`. Each cell shows median",
        "ns/pkt and Mpps received from a 30-second sweep at the",
        "stated offered load. Single-queue, single-consumer (the",
        "ceiling on the receive pipeline, not aggregate cluster",
        "throughput).",
        "",
    ]
    for (testbed, size_b) in sorted(by_section.keys()):
        section = by_section[(testbed, size_b)]
        loads = sorted(loads_per_section[(testbed, size_b)])
        modes = sorted(modes_per_section[(testbed, size_b)])
        lines.append(f"## {testbed} — frame {size_b} B")
        lines.append("")
        header = ["Mode"] + [f"{L} Mpps offered" for L in loads]
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join("---" for _ in header) + "|")
        for mode in modes:
            row = [f"`{mode}`"]
            for L in loads:
                cell = section.get(mode, {}).get(L)
                if cell is None or cell.get("ns_per_pkt") is None:
                    row.append("—")
                    continue
                ns = fmt_num(cell["ns_per_pkt"], 0)
                mpps = fmt_num(cell.get("mpps_received"), 2)
                drops = cell.get("drops_pct")
                drops_s = f"{drops:.0f}%" if isinstance(drops, (int, float)) else "?"
                zc = cell.get("zerocopy", "?")
                tag = "" if zc == "zerocopy" else f" ({zc})"
                row.append(f"{ns} ns/pkt ({mpps} Mpps), drop {drops_s}{tag}")
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    out_path.write_text("\n".join(lines) + "\n")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--results", required=True, type=Path,
                   help="root of the results tree (e.g. perf-results/)")
    p.add_argument("--out", type=Path, default=None,
                   help="output dir (default: --results)")
    args = p.parse_args(argv)

    if not args.results.is_dir():
        print(f"error: --results {args.results} is not a directory", file=sys.stderr)
        return 2
    out_dir = (args.out or args.results).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    cells = collect(args.results.resolve())
    if not cells:
        print(f"error: no afxdp cell JSONs found under {args.results}", file=sys.stderr)
        return 1

    write_csv(out_dir / "summary-afxdp.csv", cells)
    write_md(out_dir / "summary-afxdp.md", cells)
    print(f"wrote {out_dir/'summary-afxdp.csv'} and {out_dir/'summary-afxdp.md'} ({len(cells)} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
